### ISSUE TITLE
OutOf Memory error in reduction step procesing PDF

### ISSUE THREAD

**Issue by javierdelpino** [Audiveris/audiveris#378] opened 2020-04-25 14:46 UTC
QWith all de PDF files i've tried always get this error in reduction step:

 "Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded"

Can you please give me any clue about what can I have wrong in my configuration to this happend.
I have Windows 10  and Java 1.8.0_251

Thank you

**Comment by hbitteur** [comment] 2020-04-25 16:57
@javierdelpino 
You've clearly run out of memory!
Without any other information, it's hard to guess what happened.
Would you mind posting one of your input PDF files, so that we can reproduce the problem.

**Comment by javierdelpino** [comment] 2020-04-25 17:41
@hbitteur 
Thanks for your answer. Obviously I run out of memory. I tried to increment java memory with parameter -Xmx4096m  but I got the same result.
I'll send you two examples
[Afternoon-In-Paris-Boyd.zip](https://github.com/Audiveris/audiveris/files/4533617/Afternoon-In-Paris-Boyd.zip)
[Airegin2.zip](https://github.com/Audiveris/audiveris/files/4533618/Airegin2.zip)

**Comment by javierdelpino** [comment] 2020-04-26 08:40
I'm not awere having closed de issue. I reopen again.

**Comment by hbitteur** [comment] 2020-04-27 08:04
The problem is that your staves do not begin with a clef, except the very first one in page.
Check in your messages, you should have many warnings like: "Staff#N no header clef."

**Comment by javierdelpino** [comment] 2020-04-27 10:06
@hbitteur 
Thanks for your answer.
¿Is there any posibility that I can modify the Score, at any step previous to the reduction, In order to add that missing clef?

**Comment by hbitteur** [comment] 2020-04-27 15:50
@javierdelpino 
This modification has to be done very early in OMR process:
Staves are discovered at GRID step.
The following step (HEADERS) scans the beginning of every staff.

So what you have to do is:
1. Process the score until GRID step,
2. Manually insert "artificial" clefs,
3. Process the other steps.

I just tried this sequence, and ... it did not work because the HEADERS step tries very hard to retrieve clef pixels, and it finds none!

So I attempted a small modification in the code to handle the case where there is *already* a clef, even though it's a manual one. And it now works.

The modification has been committed as fadd19cda451aff711b27d64d38c61f9177fac24
For this, you will have to pull Audiveris and checkout its "development" branch, which will give you all the features that are not yet officially released. Make sure to use Java 11 (vs Java 8 for 5.1 release).

Also, pay attention to where you manually insert the clefs. The *center* of the clef must be **inside** the staff, which means after the starting barline. But not too far on right either, otherwise you'll miss the accidental sharp sign.
See the insertion I did below. Granted, this is visually not that pretty, but it works. :-)
![image](https://user-images.githubusercontent.com/22053634/80391070-8b89b900-88ad-11ea-9dff-3232708b4755.png)

**Comment by javierdelpino** [comment] 2020-04-27 17:17
@hbitteur 
Thanks for your answer. I'll try the workaround you sugest.
¿Is there a windows beta release with the commit you have made or should I compile myself? I have no development platform ready at this moment. It's been long since I use it last time. May be in the future if I get more time start developing again

**Comment by hbitteur** [comment] 2020-04-27 17:20
No, there is no beta release for this.
You have to recompile if you want to use it immediately.

There is a pending 5.2 release in the works, but it's a matter of several weeks if not months from now.

**Comment by javierdelpino** [comment] 2020-04-27 17:34
@hbitteur 
I'll try to use this release till the next.
Thanks for your work I think is excelent and very useful.

**Closed** 2020-04-27 17:35 UTC
