### ISSUE TITLE
Not Starting on Windows 10

### ISSUE THREAD

**Issue by FeaXR** [Audiveris/audiveris#602] opened 2022-11-29 23:57 UTC
I cannot get Audiveris to start on Windows 10. A single empty cmd window pops up for a fraction of a second, then closes itself and the program never launches

**Comment by hbitteur** [comment] 2022-11-30 08:34
We can suspect a too old java version. Please make sure you have Java 17 installed.

But rather than guessing, the correct approach would be to read the error messages. Unfortunately, the cmd windows disappears before you can read them. So, please do the following:
1. Open a cmd windows on your own (so that it remains open)
2. From this window, launch Audiveris program manually from the command line. By default its "C:\Program Files\Audiveris\bin\Audiveris.bat"
3. Finally read the messages and post them on this forum so that we can help you further.

**Comment by FeaXR** [comment] 2022-11-30 09:46
Thank you, It solved the issue and the program now launches
Now I have an exception thrown with the following error:
Error in performing [LOAD, BINARY] java.util.concurrent.ExecutionException: de.intarsys.pdf.content.CSError: Image can't be rendered (java.util.NoSuchElementException)

**Comment by hbitteur** [comment] 2022-11-30 09:52
Could you post the input file so that I can reproduce the error?
It seems to be a PDF file.

Also, tell us if your Audiveris version comes from Windows installer or if you built it on your own. I'd guess the former, but please confirm.

**Comment by FeaXR** [comment] 2022-11-30 11:43
The file comes from a book's PDF version, that I split into several parts and this is one of them.

There are two things that come to my mind:
It has accented letters (í, á, ú, ű, ó, ö, ő) specific to the hungarian language, maybe that could be a problem?
It's not the cleanest of scores, as I think it's from a scanned and kind-of cleaned up version of the book. I wasn't sure if Audiveris expects a clean vector-defined PDF or can work with a scanned PDF, so I tried to input the same file converted to JPG, which Audiveris could open, but couldn't parse correctly, though at least it has given a correct output instead of an error.


The version of Audaveris comes from the latest Windows installer.

The PDF:
[240.pdf](https://github.com/Audiveris/audiveris/files/10122715/240.pdf)
The image versio
![240](https://user-images.githubusercontent.com/55257249/204787420-9cca4578-aab1-4f31-99ef-1a8f6ae831b7.jpg)
n:

**Comment by hbitteur** [comment] 2022-11-30 16:13
The language impacts only the OCR part, not the OMR part.
To be able to OCR the title and lyrics of your input score, you need support for Hungarian language which is not included by default.
Only DEU, ENG, FRA and ITA are part of the installation.

So, you will have to download and install proper Hungarian data files from [Tesseract web site](https://github.com/tesseract-ocr/tessdata). Choose file `hun.traineddata` and store it locally, next to the other language files in `tessdata` folder which is generally pointed by TESSDATA_PREFIX environment variable.

As an example, here is my current configuration:

>$ echo $TESSDATA_PREFIX
> C:\Program Files (x86)\Tesseract-OCR\tessdata

and say French language is at:
> C:\Program Files (x86)\Tesseract-OCR\tessdata\fra.traineddata

This process is documented in this [Audiveris Handbook section](https://audiveris.github.io/audiveris/_pages/install/sources/#dependencies) although this old doc still points to a now obsolete URL of Tesseract data files. So, use the link posted higher in this message.

**Comment by hbitteur** [comment] 2022-11-30 16:28
Regarding your PDF file, even the most recent development version of Audiveris fails on this file with the same error message as yours.
We cannot debug what is happening with this PDF file, because JPodRenderer, the library in charge of loading PDF files, is beyond our control.

Your approach (i.e. deriving a JPG version) is a good workaround.
But pay attention to image resolution: Audiveris requires around 20 pixels for staff interline (which is typical for a 300DPI scan), but the jpg version you have posted has only 8 pixels for staff interline.

**Comment by FeaXR** [comment] 2022-11-30 20:09
I converted it using an online tool ( ilovepdf.com ) and it didn't give me an option to change the resolution, so I loaded up the file in Photoshop and exported it to a jpg. To achieve the required 20 pixels per staff interline, the image was really big, and Audiveris displayed a popup saying that the image is too big, then proceeded to load it up and convert it. Of course the conversion is not perfect, but it gives me a good enough result that I can touch up easily. Some notes and natural symbols were left out, but it can be hand-fixed quickly.

Thank you so much for all your help!

**Comment by hbitteur** [comment] 2022-12-10 09:14
> I'm still surprised that Audiveris opened the file, despite it being too large.

It is just a warning, calling user's attention on the fact that needed resources will be huge, perhaps leading to out of memory error or endless processing.

Could we close this issue now?

**Comment by bdovhan** [comment] 2022-12-11 08:32
I have the same problem, doesn't start on Windows 10. How do I figure out if it cannot find JAVA or problem is with something else? Do I need to install JRE or JDK?

**Comment by bdovhan** [comment] 2022-12-11 08:33
When I run it from the CMD i see the following

```
>C:\Tools\Audiveris\bin\Audiveris.bat

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by bdovhan** [comment] 2022-12-11 08:45
Ok, installed JDK 17, looks like this helped.

However, looks like when I try to import image, it seems to be rotated despite originally it has correct position and the tool fails to transcribe. How do I make it work?

**Comment by bdovhan** [comment] 2022-12-11 08:48
Tried to rotate it wrong, but this doesn't help :(

**Comment by bdovhan** [comment] 2022-12-11 08:51
![image](https://user-images.githubusercontent.com/22215663/206894683-0da56149-1eb4-4b2d-8414-422f89a23663.png)

**Comment by bdovhan** [comment] 2022-12-11 08:52
These are original files I tried to import
![image0](https://user-images.githubusercontent.com/22215663/206894706-b2015c58-2dd6-47cb-94e6-07eba979a77e.jpeg)
![image1](https://user-images.githubusercontent.com/22215663/206894711-5a8e737d-a17b-453d-8031-899444dc5df9.jpeg)

**Comment by hbitteur** [comment] 2022-12-11 15:39
@bdovhan 
As you discovered, if no suitable Java is installed this application can't work.

Now, regarding to the input image, I can confirm that no rotation is ever performed by Audiveris.
I just loaded your image (here below the  TaLouange.jpeg file) and indeed it appears rotated 90 degrees to the left in Audiveris window!
Loading a PDF is delegated to JPodRenderer while any other format (including .jpeg) is performed by class javax.imageio.ImageIO which is part of Java platform.

So, I tried a couple of thing, using XnView (freeware) to convert the original input file into a .png and into a .jpg file.
Here are the 3 versions:

>$ ls -ltr Ta*
>-rwxrwx---+ 1 herve herve  4717814 Dec 11 13:00 TaLouange.jpeg
>-rwxrwx---+ 1 herve herve 14011742 Dec 11 13:06 TaLouange-saved.png
>-rwxrwx---+ 1 herve herve  2078508 Dec 11 13:09 TaLouange-saved.jpg

And here are their loading into Audiveris (using the same order)
>[TaLouange] 1 sheet in D:\soft\cases\Issue-602\TaLouange.jpeg
>[TaLouange] Loaded image 1 4032x3024 from D:\soft\cases\Issue-602\TaLouange.jpeg
>[TaLouange] Converting max RGB to gray

>[TaLouange-saved] 1 sheet in D:\soft\cases\Issue-602\TaLouange-saved.png
>[TaLouange-saved] Loaded image 1 3024x4032 from D:\soft\cases\Issue-602\TaLouange-saved.png
>[TaLouange-saved] Converting max RGB to gray

>[TaLouange-saved] 1 sheet in D:\soft\cases\Issue-602\TaLouange-saved.jpg
>[TaLouange-saved] Loaded image 1 3024x4032 from D:\soft\cases\Issue-602\TaLouange-saved.jpg
>[TaLouange-saved] Converting max RGB to gray

Note that the original image is seen as 4032x3024 (which is wrong)
The one converted to .jpg is seen as 3024x4032 (corrrect)
The one converted to .png is seen as 3024x4032 (correct)

Don't ask me to explain the behavior of the .jpeg file.
At least you have a workaround.

**Comment by bdovhan** [comment] 2022-12-12 11:45
> @bdovhan As you discovered, if no suitable Java is installed this application can't work.
> 
> Now, regarding input image, I can confirm that no rotation is ever performed by Audiveris. I just loaded your image (here below the TaLouange.jpeg file) and indeed it appears rotated 90 degrees to the left in Audiveris window! Loading a PDF is delegated to JPodRenderer while any other format (including .jpeg) is performed by class javax.imageio.ImageIO which is part of Java platform.
> 
> So, I tried a couple of things, using XnView (freeware) to convert the original input file into a .png and into a .jpg file. Here are the 3 versions:
> 
> > $ ls -ltr Ta*
> > -rwxrwx---+ 1 herve herve  4717814 Dec 11 13:00 TaLouange.jpeg
> > -rwxrwx---+ 1 herve herve 14011742 Dec 11 13:06 TaLouange-saved.png
> > -rwxrwx---+ 1 herve herve  2078508 Dec 11 13:09 TaLouange-saved.jpg
> 
> And here are their loading into Audiveris (using the same order)
> 
> > [TaLouange] 1 sheet in D:\soft\cases\Issue-602\TaLouange.jpeg
> > [TaLouange] Loaded image 1 4032x3024 from D:\soft\cases\Issue-602\TaLouange.jpeg
> > [TaLouange] Converting max RGB to gray
> 
> > [TaLouange-saved] 1 sheet in D:\soft\cases\Issue-602\TaLouange-saved.png
> > [TaLouange-saved] Loaded image 1 3024x4032 from D:\soft\cases\Issue-602\TaLouange-saved.png
> > [TaLouange-saved] Converting max RGB to gray
> 
> > [TaLouange-saved] 1 sheet in D:\soft\cases\Issue-602\TaLouange-saved.jpg
> > [TaLouange-saved] Loaded image 1 3024x4032 from D:\soft\cases\Issue-602\TaLouange-saved.jpg
> > [TaLouange-saved] Converting max RGB to gray
> 
> Note that the original image is seen as 4032x3024 (which is wrong) The one converted to .jpg is seen as 3024x4032 (corrrect) The one converted to .png is seen as 3024x4032 (correct)
> 
> Don't ask me to explain the behavior of the .jpeg file. At least you have a workaround.

Does this mean I would try to convert a file to a different format and then convert it back or just use a different format?

**Comment by bdovhan** [comment] 2022-12-12 11:45
Also, I think I have installed JDK, but not sure if that was required, maybe I could just install JRE...

**Comment by hbitteur** [comment] 2022-12-12 11:50
> Also, I think I have installed JDK, but not sure if that was required, maybe I could just install JRE...

To my knowledge, Oracle no longer releases JRE's, but JDK's only.

Regarding the input format, simply convert your image one-way to either .jpg or .png and feed Audiveris with the converted file.

**Comment by bdovhan** [comment] 2022-12-12 19:25
> > Also, I think I have installed JDK, but not sure if that was required, maybe I could just install JRE...
> 
> To my knowledge, Oracle no longer releases JRE's, but JDK's only.
> 
> Regarding the input format, simply convert your image one-way to either .jpg or .png and feed Audiveris with the converted file.

Ok, I have performed the double conversion, from jpg to png and then back to jpg and it seems to be working. However, there are problems with ocr-ing my file. Are there some guidelines how to make it work to read it propertly? I tried to rotate a source file in -1 or  -2 degrees but this didn't help, but make the transcribe process to fail... 
While the original file was transcribed wrong, but at least without an error

**Comment by bdovhan** [comment] 2022-12-12 19:27
Looks like in the original file the program struggles to recognize horizontal lines and I haven't figured out how to fix it or how to help the program to transcribe it.  I did figure out at least how to add the missing note or accent

**Comment by FeaXR** [comment] 2022-12-12 21:18
> > I'm still surprised that Audiveris opened the file, despite it being too large.
> 
> It is just a warning, calling user's attention on the fact that needed resources will be huge, perhaps leading to out of memory error or endless processing.
> 
> Could we close this issue now?

Yes, it's all solved. I'll close it

**Comment by hbitteur** [comment] 2022-12-13 08:57
> Ok, I have performed the double conversion, from jpg to png and then back to jpg and it seems to be working.

@bdovhan 
There is a misunderstanding here.
You don't have to perform any "double conversion".
I simply told you that the loading didn't succeed with your original file (the .jpeg one) because it appeared rotated.
I also reported the results of my experiments:
- Your file converted to .jpg works
- Your file converted to .png works

So pick up the conversion you like and go with it. No need for back & forth conversions.

Now, I noticed the input image is of poor quality. I was able to transcribe it but with a bunch of manual corrections.

**Comment by hbitteur** [comment] 2022-12-13 09:06
> > Could we close this issue now?
> 
> Yes, it's all solved. I'll close it

And I'm closing it because the issue title is "**Not starting on Windows 10**" and this issue has been clarified and solved.

Recall: A sound policy is to keep issues focused. The motivation is to help other users browse this forum.
So if a new topic requires discussion, let's open a new issue for this new topic and let's close it when it is finished.

**Closed by hbitteur** 2022-12-13 09:06 UTC
