### ISSUE TITLE
double beams overlayed in view, output as 16th

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#103] opened 2018-03-04 09:01 UTC
[And so it Goes_02.zip](https://github.com/Audiveris/audiveris/files/1778314/And.so.it.Goes_02.zip)

In this score I have some double beams that are overlayed (almost not visible) and output to export, leading to mistakes in rhythm:

- measure 2, 2nd stave: a half beam over a normal beam
- measure 5, last stave: tripple half beam in output
- measure 8, 5th stave: tripple bar

The 2nd bar was set by me - but only once...

**Comment by hbitteur** [comment] 2018-09-15 15:16
The root cause is the poor quality of image, with beams composed of tiny bits of black and white.
It's not a bug.
Some manual editing was able to correct all these items.
Closing the issue

**Closed by hbitteur** 2018-09-15 15:16 UTC
Labels: bug
