### ISSUE TITLE
I don't understand why measure is red

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#509] opened 2021-09-13 17:56 UTC
Hi...  I'm attaching a score and a screenshot.  Why is the first measure marked red by Audiveris?  I can't understand what the possible error is and where it is.  Thank you

[chopin-étude_op10n12.pdf](https://github.com/Audiveris/audiveris/files/7156437/chopin-etude_op10n12.pdf)
![screenshot 2021-09-13 17:24:08](https://user-images.githubusercontent.com/64352612/133133117-b3f101b4-6b78-4a88-b312-346f59611bea.png)
 you.

**Comment by hbitteur** [comment] 2021-09-14 18:35
Root cause is a detected vertical misalignment between first chord in upper staff and first chord (rest) in lower staff.
You can manually fix this by selecting these 2 chords and make them use the same time slot.

Running latest development version (5.2.4-alpha) on your example works correctly (alignments are better handled):
![image](https://user-images.githubusercontent.com/22053634/133312351-a0a12683-e36c-440f-befe-14d856d0ea51.png)

So, either fix the pb manually, or pull and build from the development version, or wait for 5.2.4 hotfix release.

**Comment by hbitteur** [comment] 2021-09-15 19:51
FYI, 5.2.4 has just been released

**Comment by hbitteur** [comment] 2021-11-09 09:41
Problem fixed, closing this issue.

**Closed by hbitteur** 2021-11-09 09:41 UTC
