### ISSUE TITLE
problems to detect flag-up in certain scores

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#470] opened 2021-02-23 13:26 UTC
Flags up are sometimes badly recognized. Instead recognition detects a ")" as text.
What is curious: after deletion of the bracket and selection of the glyph, the flag is always as top classifier in the classifier proposal list. Here an example with many cases:
![get under sail](https://user-images.githubusercontent.com/33522630/108850016-21cc5f80-75e3-11eb-88cb-9eb155c276fc.jpg)

**Comment by hbitteur** [comment] 2021-02-24 13:24
Yes, I noticed this while working on your score.

The root cause is in the TEXTS step, where some flags are wrongly OCR'ed as parenthesis.
Nothing has been changed for a long time in this TEXTS step, which is performed by Tesseract OCR.
I'm afraid there is nothing to be tried in the short term (read: before 5.2 is out)

In a longer term, we can think of a kind of "pre-OCR" processing where Audiveris engine would explicitly identify candidate text areas before calling OCR on each of them. And of course, this pre-OCR would avoid regions of stems and note heads.

**Comment by hbitteur** [comment] 2021-08-06 08:03
In fact, testing the input score with Audiveris 5.2.3, most of the flag candidates are not captured as parentheses by OCR.

Later, in the SYMBOLS step, they are simply not recognized as flags, because the corresponding flag shape gets a too low recognition grade.
We'll have to investigate why, perhaps because the neural network has not been trained correctly.

Update: After additional training, flags are now correct.
Closing...

**Closed by hbitteur** 2021-08-06 08:03 UTC
