### ISSUE TITLE
Audiveris software no ghost note instances 

### ISSUE THREAD

**Issue by Breezybeater** [Audiveris/audiveris#681] opened 2023-10-21 06:54 UTC
I was transcribing a music sheet with these notes; 
![image](https://github.com/Audiveris/audiveris/assets/148612450/b03e16a6-fbba-4f06-afab-2e342486f8fd)

However this then translated to, and audiveris is mentioning that there is "No ghost instance for HW_REST_set"; 
![image](https://github.com/Audiveris/audiveris/assets/148612450/2e3d20e4-9e7d-4c80-a778-07a70474bd79)
Any help would be appreciated!

**Comment by hbitteur** [comment] 2023-10-22 17:15
As human beings, we can rather easily understand that the first chord in the upper staff is composed of void heads, whose duration is impacted by double augmentation dots (even though their "dot" shape is closer to a parallelogram than to a circular dot).

Seen from the  glyph classifier, which works on a glyph in isolation, such double augmentation dots look like small horizontal rectangles which are "recognized" as whole/half rest shape. 
Their shape is consistently named **HW_REST_set**, because the same physical shape applies both to **H**alf rests and to **W**hole rests.

Only the precise location with respect to staff lines may disambiguate between half and whole rest.
This computation is done by the OMR engine during its SYMBOLS step, and the result is often correct; but not always, especially when the glyph is located rather far from staff.

This dependency on precise location is the reason why this computation is **not** done when the user presses the HW_REST_set button in the raw outputs of the glyph classifier (as you did).
Simply because the user is in the driver's seat: he can easily tell which shape it is precisely:
- Either by using the popup menu (right-click on the glyph), then following `Glyphs` > `Assign` > `Rests` > `WHOLE_REST` or `HALF_REST`.
- Or by a drag 'n drop from the proper `WHOLE_REST` or `HALF_REST` button in the shape board.

I agree that the generic message "No ghost instance for HW_REST_set" is a bit cryptic.
At least now you have the explanation. :-)

But, these are double dots not rests!
The problem is you'll find no way to pick up a single-dot glyph, because these dots are merged into one wide glyph in the input image.
You will need to resort to manually drag 'n drop from the augmentation dot button available in the `HeadsAndDot` shape set of the shape board:
![image](https://github.com/Audiveris/audiveris/assets/22053634/014f72eb-e64f-4921-bba4-2d1f177a00ed)
My advice: select the "`FinaleJazz`" musical font in the Book parameters.

**Closed** 2023-10-29 11:50 UTC
