### ISSUE TITLE
'indentation' document option seems always on in development version

### ISSUE THREAD

**Issue by phdm** [Audiveris/audiveris#648] opened 2023-05-01 19:44 UTC
Hello,

I use the development version on scores that have a indented coda section,  I have not set the 'indentation' option ( rely on relative system indentation to detect the start of a new movement ), but nevertheless audiveris exports the mxl file in two parts called ...mvt1.mxl and ...mvt2.mxl.  I have tried to set the option, but the result is exactly the same.  In the version used on 'musescore''s site, however, the score is not split.  I don't know which version is used on musescore's site, nor how the options are set there.

**Comment by hbitteur** [comment] 2023-05-09 08:40
Closing this issue (648) which is a duplicate of issue #647

**Closed by hbitteur** 2023-05-09 08:40 UTC
