### ISSUE TITLE
Use manual correction items as selectable tools [feature request]

### ISSUE THREAD

**Issue by hekkup** [Audiveris/audiveris#324] opened 2019-11-30 19:13 UTC
I'm manually correcting a recognition result. The sheet music scan I'm using has poor quality so there are a lot of errors. Dragging and dropping correction items is tedious, so how about being able to select a single type of correction item, such as black note head or a quarter rest, and use it repeatedly as many times as needed? That would speed up the manual correction a lot.

**Comment by hbitteur** [comment] 2019-11-30 19:47
Hmm, the program needs some gesture from the user indicating his will to insert a new object (of the same type of the previous one in your case) at a given location.

Today, this is done via a drag n' drop gesture.
What is your proposed gesture to suppress the drag n' drop?

**Comment by hekkup** [comment] 2019-11-30 20:01
I suggest a simple click. Selecting areas could be done with a separate tool, or e.g. shift+clicking.
If this messes with the current functioning, there could be two usage modes from which the user could select the more useful for him/her. I guess that would depend on the recognition result: which kind of work is required most.

**Comment by hbitteur** [comment] 2019-11-30 21:02
@hekkup 
Since you are making a heavy use of correcting actions, I would suggest that you give a try to the new UI.
It is not released yet, the documentation is still to be written, but most of the features are available. Simply pull the "geometric-ui" branch.

Compared with 5.1 UI, the new one offers the ability to move and reshape almost all items.
Basically, you have to set the item into the "edit" mode, for example via a double-click on the item, and then you can use the various handles to mode/modify the item. 
The precise behavior depends on the kind of item being edited.

So, please try it and share your early feedback with us.

**Comment by hbitteur** [comment] 2019-11-30 21:06
Regarding your suggestion: "I suggest a simple click. Selecting areas could be done with a separate tool, or e.g. shift+clicking."
This indeed will mess up the current features. But OK, perhaps a temporary mode could allow this. We have to think this over.

**Comment by Bacchushlg** [comment] 2019-12-01 07:50
I propose to extend the shortcuts with an additional function to repeat the last shape assignment. E.g. "0" which will extend the last added assignments 1...5 from the list of basic classifiers with the left-most of the shape list. Should be as effective as the initial proposal but keep the general concept.

**Comment by hbitteur** [comment] 2019-12-01 09:50
Beware, the new shortcuts (1..5) apply to the selected glyph. In that case I agree that shortcut 0 could be used to indicate "the last shape used".

But when you have no selected glyph, today you have to resort to a drag n' drop gesture to indicate where the new item is to be located.

To summarize, when creating a new Inter item we need 2 informations:
1/ The shape
2/ The location

The "0 shortcut" provides the shape, not the location (except when a glyph is already selected, since the glyph center is taken as the target location).

@hekkup proposal is to use a simple mouse click to provide the location, taken the shape as given since it is a kind of repetition.

**Comment by Bacchushlg** [comment] 2019-12-01 11:23
From the practice I assume that simple click rather often is not working. Instead a lasso is needed. So, first select and then do the action is more straight forward. And in the end the workflow will be rather quick, because the user does not need to move the cursor for the action. It's simply select item, press "0", select next,....

**Comment by hbitteur** [comment] 2019-12-01 18:32
@Bacchushlg said "So, first select and then do the action..."

Here, you mean selection of some item (typically a glyph or an inter). Fine.

The problem is when you have nothing to select, no glyph clearly delimited, no inter, ... In that case you still need a way to indicate the target location. So, how can we do that? hekkup suggests to use a click. What else can we think of?

**Comment by hekkup** [comment] 2019-12-01 18:38
How much different the feature I suggested would be from ordinary notation applications such as Musescore? Not much. So maybe that world can be used as a reference here?

**Comment by hekkup** [comment] 2019-12-01 18:47
@hbitteur I tried geometric-ui branch. To me it felt similar to the master branch in regard of dragging and dropping shapes.

I think key shortcuts would also help. What you have said about "0" sounds good, but in principle each or most of the different shapes could have their own key.

**Comment by hbitteur** [comment] 2019-12-01 18:49
For Audiveris UI, MuseScore is already considered as a reference (most of handles behavior for inter edition were taken from MuseScore). So MuseScore is a reference both from data model point of view and from end-user gesture point of view.

However, purposes of MuseScore and of Audiveris are far from being identical. Typically Audiveris focuses on fidelity to the input image while MuseScore does not.

That being said, I totally agree with the proposal of not reinventing the wheel but rather sticking to MuseScore approach whenever appropriate.

**Comment by hbitteur** [comment] 2019-12-01 18:54
The geometric-UI branch does not modify dragging and dropping. It focuses on the ability to modify the items once they have been manually dropped (or once they have been poorly recognized by the OMR engine).

So far in the master branch, you can only assign or delete an item. No change in location, no resizing (which is often needed for beams, slurs, etc).

**Comment by hekkup** [comment] 2019-12-01 18:58
Editing beams and slurs worked great in geometric-UI branch.

**Comment by hbitteur** [comment] 2019-12-02 08:31
Okay, I will implement a "Note input" mode à la MuseScore, governed by a dedicated toggle button. Under this mode, a simple mouse click will insert a new instance of [current Inter class] centered on the mouse location.

**Comment by hbitteur** [comment] 2019-12-03 18:59
First implementation of "repetitive input mode"  is now available in commit f6008bb43f9560faeb7fc62347bc36e5374f9fb8

Under this mode (selected/deselected via a new icon, figuring a green "plus" sign), the user is meant to repetitively enter the same item shape via a simple mouse press/drag/release sequence in the sheet view.
The item shape is copied from the last shape assigned (visible at beginning of assigned shapes). If no previous assigned shape exists, a drag n' drop from the shape board is necessary to initiate the sequence of inputs.
Similarly, even under the repetitive mode, the user can always use a standard dnd. This has the side effect to set a new latest shape.

Feel free to test and comment.

**Comment by oleedd** [comment] 2019-12-05 15:52
I don't see any ability to move and reshape items. Used this to install: https://github.com/Audiveris/audiveris/wiki/Installation

**Comment by Bacchushlg** [comment] 2019-12-05 17:13
genial!
I just tried it with a score that had a couple of missing flags - editing is at least double as fast than before.
What is also fine is the possibility to select another shape (drag-n-drop) and continue with this - no need to leave this mode.

Of course there is room for a minor improvement: what about a short-cut to toggle the mode? One of the not-used function keys would be fine.

**Comment by oleedd** [comment] 2019-12-05 17:19
I don't see any ability to move and reshape items. Used this to install: https://github.com/Audiveris/audiveris/wiki/Installation

**Comment by hbitteur** [comment] 2019-12-06 08:43
@oleedd 
This feature is available only in the "geometric-ui" branch, it is not released yet. It will be in coming 5.2 release.

To try this feature today, don't use standard installation which deals only with the last release.
But clone the project, checkout the geometric-ui branch, and build the software.

**Comment by hbitteur** [comment] 2019-12-06 09:01
@Bacchushlg who said: "what about a short-cut to toggle the mode? One of the not-used function keys would be fine"
I just checked Musescore, they use 'n' to enter their note input mode and 'esc' to exit the mode. 

So, which shortcut should we use to enter the mode, 'n' or function key:
- **'n'**
   - Pro: it's MuseScore shortcut, so users won't be surprised
   - Con: none to my knowledge
- **(function key)**
   - Pro: our mode concerns many shapes not Notes only (but we could decide to restrict the shape range)
   - Con: There is no obvious candidate. Also, function keys are a scarce resource.

My vote goes to 'n'

**Comment by oleedd** [comment] 2019-12-06 09:08
> But clone the project

So the first step is the same.
>checkout the geometric-ui branch

What does it mean?

**Comment by oleedd** [comment] 2019-12-06 09:09
>But clone the project

So the first step is the same.
>checkout the geometric-ui branch

How to do this?

**Comment by hbitteur** [comment] 2019-12-06 09:16
@oleedd 
In the directory where you have just cloned the project, do:

> git pull --all
> git checkout geometric-ui

and then use gradlew to build/run the software

**Comment by hbitteur** [comment] 2019-12-06 09:20
@oleedd FYI, have a look at our wiki article [Git workflow](https://github.com/Audiveris/audiveris/wiki/Git-Workflow) which describes the workflow we (try to) use.

**Comment by hbitteur** [comment] 2019-12-06 11:25
Commit fe3894549952d7d8e38aa03a3ab5803b63568efb
Shortcut 'n' is now used to enter/exit repetitive input mode

**Comment by oleedd** [comment] 2019-12-06 17:53
It gives this:
>git pull --all

Fetching origin
Already up to date.
>git checkout geometric-ui

Switched to a new branch 'geometric-ui'
Branch 'geometric-ui' set up to track remote branch 'geometric-ui' from 'origin'.
>gradlew.bat clean build

Execution failed for task ':compileJava'.

**Comment by hbitteur** [comment] 2019-12-06 18:00
No further detail on why java compilation failed?
Which java version do you use?

**Comment by oleedd** [comment] 2019-12-06 19:08
Java 8 Update 151. It worked for previous versions of Audiveris.
![](https://i.imgur.com/zXWlLVH.jpg)

**Comment by hekkup** [comment] 2019-12-06 21:30
The repetition mode works great. :) It's a great time and click saver, and will add to the usability of Audiveris.

The next feature request: entering shapes would be even faster if I shouldn't move the mouse so much in order to move the scroll bars. So, I suggest taking middle mouse button (/wheel) into use so that you could pan the view with it. Inkscape is an example about what I mean. Click down: lock the position which to drag. Move mouse: move the locked position.
Should I make a new feature request issue for this? Ok I think I'll do it.

**Comment by hbitteur** [comment] 2019-12-07 08:39
@oleedd 
Java 8 was for 5.1 release.
On development version, preparing 5.2, we now use Java 11.
This is certainly the reason for your compilation errors.

Also, since the new UI features developed in "geometric-ui" are now OK, I have just merged "geometric-ui" back to "development" branch.  The idea is now to switch to preparation of 5.2 release.
So you can use the development branch for now.

**Comment by oleedd** [comment] 2019-12-07 15:24
The thing is I very need Java 8 for another program. How to be?

**Comment by hbitteur** [comment] 2019-12-07 17:57
I don't have any immediate answer, except modifying the PATH environment variable.
This is not, strickly speaking, an Audiveris issue.
If I were you, I would search on the Internet for something like "running multiple java versions".

**Comment by Bacchushlg** [comment] 2019-12-08 08:43
I propose to close this issue. The described problem is solved, in my opinion.

**Comment by hbitteur** [comment] 2019-12-08 09:20
@Bacchushlg Let's wait for @oleedd to confirm that he can actually use latest Audiveris version.

Also, I still need to implement the shifting (panning?) of sheet view triggered by mouse wheel press & drag.

**Comment by hbitteur** [comment] 2019-12-08 09:35
Support for mouse wheel press & drag is now available in development branch (commit f65034c3144743fc0793e9c5ac431b349c03b4c5)

**Comment by oleedd** [comment] 2019-12-08 12:53
![](https://i.imgur.com/Uznr4NY.png)
What version should be?

**Comment by hbitteur** [comment] 2019-12-08 14:05
@oleedd 
Use Java 11.
Check with command: java -version

**Comment by oleedd** [comment] 2019-12-08 14:19
I use version 11.0.5. cmd doesn't know "java" command.

**Comment by oleedd** [comment] 2019-12-08 14:21
I use version 11.0.5. It is Java 11 with update 5. cmd doesn't know "java" command.

**Comment by hbitteur** [comment] 2019-12-08 14:25
Check your PATH, which should contain a reference to JAVA_HOME.
Check JAVA_HOME as well.

**Comment by oleedd** [comment] 2019-12-08 14:35
JAVA_HOME wasn't set. But I set it by hand. It started to see the version but gives "Could not determine java version from 11.0.5".

**Comment by hbitteur** [comment] 2019-12-08 15:13
Sounds like a messy configuration to me. It's hard to debug it "remotely".
I'd suggest to start over from a clean basis:

1. uninstall all your Java environments completely
2. purge PATH from any reference to java
3. remove variable JAVA_HOME
4. reinstall the Java environments you need from scratch
5. finally, check your PATH and JAVA_HOME values and modify them if necessary to play with your multiple Java environments.

**Comment by oleedd** [comment] 2019-12-08 15:20
I uninstalled all before installation. I used this file to install Java:
`jdk-11.0.5_windows-x64_bin.exe`
But it gives the same even with the clear 11 version:
`Could not determine java version from '11'.`

**Comment by hbitteur** [comment] 2019-12-08 16:19
Please post value of your PATH environment variable. So we can check it.

**Comment by oleedd** [comment] 2019-12-08 16:35
I just changed it to `%JAVA_HOME%\bin` as found in one guide but it didn't help.

**Comment by hbitteur** [comment] 2019-12-08 16:47
And your PATH is?

**Comment by hbitteur** [comment] 2019-12-08 16:49
I mean the full value of PATH
For Windows, use: 
> echo %PATH%

**Comment by oleedd** [comment] 2019-12-08 16:52
C:\Program Files\Java\jdk-11.0.5\bin;C:\Program Files (x86)\Intel\iCLS Client\;C
:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\Sys
tem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\In
tel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Manageme
nt Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine
 Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Componen
ts\IPT;C:\Program Files (x86)\Paragon Software\Partition Manager 12 Professional
\bluescrn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Fil
es (x86)\Common Files\Propellerhead Software\ReWire\;C:\Program Files\Common Fil
es\Propellerhead Software\ReWire\;C:\Program Files\Git\cmd

**Comment by hbitteur** [comment] 2019-12-08 17:19
I typed "Could not determine java version from '11'." in google search.

According to this article [https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2](https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2) there might be a problem with either gradle or gradlew or both with java version.

**Comment by oleedd** [comment] 2019-12-08 17:24
I tried older versions of gradle. They see Java 11 but many errors in compiling like "cannot find symbol" etc. Can you try to build in Windows?

**Comment by oleedd** [comment] 2019-12-08 19:56
Maybe it generally doesn't work on Windows after moving to Java 11.

**Comment by oleedd** [comment] 2019-12-08 20:02
Maybe it generally stopped to work on Windows after moving to Java 11.

**Comment by hbitteur** [comment] 2019-12-09 07:45
On development branch, we build using java 11, whatever the OS.
I personally use Windows 10 and Java 11.0.3

**Comment by oleedd** [comment] 2019-12-09 08:57
I use Windows 7. Tried Java 11.0.3 but it gives the same:
`Could not determine java version from '11.0.3'.`
So gradlew sees Java and its version but don't know it. Old version of gradlew?

**Comment by oleedd** [comment] 2019-12-09 11:41
Gradle supports Java 11 only from the 5.0 version.
https://docs.gradle.org/5.0/release-notes.html
But there is a link for Gradle 4.6 in your `gradle-wrapper.properties` file. It doesn't even support Java 10 (what requires Gradle 4.7). In what way did you build Audiveris?

**Comment by hbitteur** [comment] 2019-12-09 14:21
Here is the current content of gradle-wrapper.properties file:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```
I can't read any 4.6 stuff, but rather a 4.10.2
If you cloned Audiveris to a fresh directory, you should have the same content (including this gradle-wrapper.properties file) than mine

**Comment by oleedd** [comment] 2019-12-09 15:23
But I cloned and have another:
```distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists```

**Comment by oleedd** [comment] 2019-12-09 15:25
But I cloned and have another:
```distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```
And here the same:
https://github.com/Audiveris/audiveris/blob/master/gradle/wrapper/gradle-wrapper.properties

**Comment by oleedd** [comment] 2019-12-09 15:27
But I cloned and have another:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```
And here the same:
https://github.com/Audiveris/audiveris/blob/master/gradle/wrapper/gradle-wrapper.properties

**Comment by oleedd** [comment] 2019-12-09 16:15
>Also, since the new UI features developed in "geometric-ui" are now OK, I have just merged "geometric-ui" back to "development" branch. The idea is now to switch to preparation of 5.2 release.
So you can use the development branch for now.

I understood that as to again install by these steps:
https://github.com/Audiveris/audiveris/wiki/Installation
No? Or need to check out "development" as it was with "geometric-ui"? The thing is when there were updates for implicit tuplets, installing by these steps worked.

**Comment by oleedd** [comment] 2019-12-09 20:48
I installed it.
BTW, better to combine "Installation" and "Git Workflow" articles and emphasize commands for changing branches. I generally didn't know that github has branches.
The best would be a little guide to clone only one needed branch.
https://stackoverflow.com/questions/4811434/clone-only-one-branch

Good job! But:
Any way to make input beams thinner? They merge into one in 16-th notes.
![](https://i.imgur.com/voNGbR5.png)
Repetitive input works after first dragging but it should be independent - work right away as well as in note editors.
Better to make items real (green, not shadow) while dragging because it is badly visible.

**Comment by hbitteur** [comment] 2019-12-10 09:50
This issue ("_Use manual correction items as selectable tools (feature request)_") has been fully discussed and is now correctly implemented.

There is always room for issue / enhancement request in Audiveris project, but please **let us use separate issues for separate topics**. Otherwise there can't be any effective issue management.

I'm closing this particular issue now.

**Closed by hbitteur** 2019-12-10 09:50 UTC
