### ISSUE TITLE
Audiveris saves/exports to files not recognized by Windows 10

### ISSUE THREAD

**Issue by radegandor** [Audiveris/audiveris#189] opened 2018-07-07 17:40 UTC
Hello all,

I am running into a strange issue, using Audiveris under Windows 10.
Whenever I try to save a book as .ocr or to export is as .mxl, the software seems to do it correctly: for example, if I close the program and launch it again, I can open the previously saved book.
The problem is that the existence of .ocr and .xml files is not recognized by the OS: they are not hidden, rather they simply do not show up either in Windows Explorer or via the Command Prompt, and are not available to other programs either.
Do you have any idea how to solve this issue?

Thank you for your help.

**Comment by maximumspatium** [comment] 2018-07-07 18:21
Did you try to save your files to another location (Documents) with the proper extension?

Audiveris files should have the **.omr** extension at the end of the filename whereas MusicXML files require the **.mxl** extension.

**Comment by radegandor** [comment] 2018-07-07 20:05
I tried to save to different partitions and folders, but unfortunately this had no effect.

**Comment by maximumspatium** [comment] 2018-07-07 20:11
> but unfortunately this had no effect.

Can't you see the files in the Windows Explorer? Please be more specific. I just saved a MusicXML into Documents in Windows 10. I can see the file and open it from Windows Explorer. In other words, I cannot reproduce your issue in my Windows 10 machine.

**Comment by radegandor** [comment] 2018-07-07 20:40
Hello, and thank you for your feedback. 
As I mentioned in the first post, the files are not accessible under Windows Explorer. Unfortunately I cannot seem able to post screenshots here, so I am providing a textual description.

Assume Audiveris is installed under 'D:\audiveris', and launched from the Command Prompt via '.\gradlew.bat run'. Assume I load a .pdf score, run 'Trancribe the whole book' (made of three sheets), adjust a couple of elements, and execute 'Save Book as' with file path 'D:\test.omr' (Changing folder does not change the result). The saving process seems successful and ends with a message 'Book stored as D:\test.omr'. 
The problem is, there is no file available under D, either through Windows Explorer, or for example running 'dir' or 'dir /a' from the Command Prompt! However, if I close Audiveris and reopen it, the software can correctly detect the presence of 'test.omr' under D and loads the book without problems.

**Comment by maximumspatium** [comment] 2018-07-07 21:04
Everything work for me. Stupid question, I know but did you try to search for `test.omr` ?

**Comment by hbitteur** [comment] 2018-07-08 13:18
Really strange.

@radegandor said "if I close the program and launch it again, I can open the previously saved book." So the project file (test.omr for example) really exists somewhere.

When you open the previously saved book, do you select it from "Recent books" or from "Open book"? (in the latter case, you would have to navigate to where you saved it)

**Comment by Bacchushlg** [comment] 2018-07-08 14:58
the default path uses a hidden directory:
C:\users\<your_name>\AppData\Roaming\AudiverisLtd\audiveris\data

That's the reason why I had opened issue #186

**Comment by maximumspatium** [comment] 2018-07-08 20:18
What happens when you open the file like this:

```
cd D:\testFolder
test.omr
```

When I execute these terminal commands, Windows opens a window asking me to select the application to open the file with...

**Comment by radegandor** [comment] 2018-07-08 21:11
@maximumspatium : I get your point, unfortunately no object with that name seems to exist

**Comment by maximumspatium** [comment] 2018-07-09 12:39
I'm sorry but I cannot reproduce the issue in my Windows 10 installation. It looks like you're experiencing a problem with your file system. I'd recommed to check/repair it first.

I'm going to close this issue because I cannot recognize any Audiveris failure - the software works as expected.

**Closed by maximumspatium** 2018-07-09 12:39 UTC
