### ISSUE TITLE
hidden triplet invisible under lyrics -> disable transparency would help

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#119] opened 2018-03-10 16:41 UTC
[Nr18 (3).zip](https://github.com/Audiveris/audiveris/files/1799567/Nr18.3.zip)

The export of this score created a triplet in measure 6, which I could not understand...
...until I zoomed to maximum and saw, there was a triplet-3 "under" the lyrics.
One more reason to disable the transparency for inters...

**Comment by maximumspatium** [comment] 2018-03-10 18:07
Yes, I saw it a couple of times. It happens for [this score](https://github.com/Audiveris/audiveris/files/1799441/Over.zip) as well (see the chord symbols above the 1st system).

Any text that hasn't been recognized by Tesseract during the TEXT step will be evaluated later during the SYMBOLS step leading sometimes to false positives for tuple digits. The problem is that these digits are taken **literally** causing an incorrect rhythm detection and an invalid MusicXML export. We'll need to reconsider this.

One thing I noticed when processing the above mentioned score is that the textual items labeled manually **after** the TEXT step will be evaluated again during the SYMBOLS step. That looks like a bug and should be fixed.

**Comment by Bacchushlg** [comment] 2018-04-23 06:52
Please just disable the transparency, in order to make it easier to find errors.

**Comment by Bacchushlg** [comment] 2018-04-23 07:24
I seldom work in output view, because from here I cannot do editing - and I also don't see the scan in the background.
About the proposal: it's ok to have a general setting - no need to have an additional button or something else.

**Comment by hbitteur** [comment] 2018-04-23 08:11
Here is a first version in commit 8486bcf5aaf493cc7f7f4429c2190bf3faf99957

The switch is in the View pull-down menu (toggleTranslucency).
It is not persistent and is set to true by default (just like the painting in pink of the error measures)

If we all agree, we can:
- Make it persistent (the constant will survive from one application run to the other)
- Use a toggle button in the toolbar (but an additional button increases the visual complexity...)

**Comment by hbitteur** [comment] 2018-04-23 09:39
OK for persistency.

For the entry name, "toggleTranslucency" is just the name of the toggle method in class ViewParameters.java and referenced from res/system-actions.xml
The label as displayed to the user is searched for in the related resource file named ViewParameters.properties (or ViewParameters_fr.properties for the French version).
Since this was just a very preliminary implementation, I had not modified the .properties file but I will do so now...

Done in commit df6dca867d811430b83aa9fb6341e720e854a14c

**Closed** 2018-05-21 16:18 UTC
Labels: bug
