### ISSUE TITLE
Help with rose-backgrounded measures

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#388] opened 2020-05-23 08:07 UTC
In the attached score I don't manage to correct the third measure of page 5 and the second measure of page 6, and xml output is corrupted...  Please help with them.  

(How can I do a screenshot of those only so to show them immediately...?)

thanks for any help,

rodolfo

[Caro nome che il mio cor - C Major - MN0102030.pdf](https://github.com/Audiveris/audiveris/files/4671387/Caro.nome.che.il.mio.cor.-.C.Major.-.MN0102030.pdf)

**Comment by Bacchushlg** [comment] 2020-05-24 14:04
The reason for your problem is the chord with note heads on both sides of the stem:
![image](https://user-images.githubusercontent.com/33522630/82756047-d973dd00-9dd7-11ea-9d8f-243216e530f9.png)

You can solve the problem by moving the note head to the right:
![image](https://user-images.githubusercontent.com/33522630/82756067-fc9e8c80-9dd7-11ea-8b7b-e558a75dc4ed.png)

(double click on the note head and move to the right).

The problem is a know bug - an issue can be found here #326.

**Comment by rodolfo-medina** [comment] 2020-05-24 14:29
Thank you very much for looking into it...  One more problem with page 5 is with the half `f' note in the chord on measure 2, right hand...  with that half `f', the xml output is corrupted; if I remove it, it's ok...  I think it's a matter of voices...  that note appears in green, so it overlays other notes of the same voice...  possible to change its colour...?

thanks,

rodolfo

**Comment by Bacchushlg** [comment] 2020-05-24 15:20
The problem here is the 2nd stem going downward on the same time tick. Very unconventionell...
Remove the stem of the "f" and drag-n-drop the half-note-head to the one the rests.
This should solve your problem.

**Comment by rodolfo-medina** [comment] 2020-05-24 18:41
thanks...  what you suggests solves the problem of the xml corruption but seems to produce other undesired effects on the notes that come after...  I wish rather to remove that 'f' and then add it again as part of a new different voice...  How to do that?  In Audiveris handbook I couldn't find that...  thanks

**Comment by rodolfo-medina** [comment] 2020-05-24 20:47
...another difficulty, on page 8 of the same document, are measures 5 and and 10: rose background, but I can't understand why...  please help, thanks

**Comment by Bacchushlg** [comment] 2020-05-26 20:40
about page 8:

- measure 5: I have no idea. According to what I see, the rhythm analysis worked correctly (Press F12 to view it).
- measure 8: this is a very unconventional way to notate a tremolo. But anyway: tremoloes are not recognized by Audiveris so far. The only way to solve this problem is to remove the 2nd chord of each tremolo and add it later in the notation program.
(By the way: the same applies to measure 9 - although not in rose...)

**Comment by hbitteur** [comment] 2021-08-07 14:25
About page 8:

- measure 5: Use chords popup menu to link both beam groups in "Next in Voice"
- measure 8: These are not tremolos per se, but 3-beamed chords. As for measure 5, the two beam groups in the lower side of the part should be stated as "Next in Voice".

And measures turn white.
Closing...

**Closed by hbitteur** 2021-08-07 14:25 UTC
