### ISSUE TITLE
Build tests fail due to missing files

### ISSUE THREAD

**Issue by obbrc** [Audiveris/audiveris#61] opened 2018-02-10 02:49 UTC
When I build with gradle, I have two tests failed
RunTableBindingTest. testMarshalTable due to missing data/temp/runtable.xml  and
MusicFontTest. textPrintout due to data/temp/MusicalSymbols.pdf missing.

After manually copying dev/material/MusicalSymbols.pdf to data/temp/, the build finished successfully.

The system is ubuntu 17.10,
Gradle and  details are below.

Thanks

------------------------------------------------------------
Gradle 3.2.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.8
Ant:          Apache Ant(TM) version 1.9.9 compiled on June 29 2017
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Linux 4.13.0-32-generic amd64

**Comment by hbitteur** [comment] 2018-02-10 19:34
I was able to reproduce the case for RunTableBindingTest.
What I don't understand, is that the creation of the target directory (data/temp) is coded in the createTempFolder() method, correctly annotated with `@BeforeClass`
It turns out that this method is **not** called, hence the error.
The `@BeforeClass` is however a standard annotation in JUnit API. Any idea?

Anyway, I moved the creation of the temp folder to the method testMarshalTable() itself, and the test now passes. But we still need an explanation regarding `@BeforeClass` being ignored. Perhaps a too old version of JUnit is actually used?

**Comment by hbitteur** [comment] 2018-02-10 19:42
Googling about this case, I found many posts complaining about BeforeClass method not being called.
For example, see [this one](https://stackoverflow.com/questions/733037/why-isnt-my-beforeclass-method-running), which tells that a few conditions must be met, including this one: the test class **should not extend TestCase**.
Unfortunately, RunTableBindingTest extends BaseTestCase which extends TestCase.

**Comment by hbitteur** [comment] 2018-02-11 19:06
Now, I have removed all the @BeforeClass and similar annotations.
I have also corrected the MusicFontTest to work even if folder "data/temp" does not exist yet.

All tests are now OK.
I'm thus closing this issue.

**Closed by hbitteur** 2018-02-11 19:06 UTC
Labels: bug
