### ISSUE TITLE
How to read 12/8 Timing

### ISSUE THREAD

**Issue by WilloZA** [Audiveris/audiveris#210] opened 2018-11-28 08:05 UTC
Is it possible to read 12/8 timing?

I notice in OmrShape.java there is -> timeSig12over8("12/8 time signature"),

Below is an example of the sheet music before transcribing:

![image](https://user-images.githubusercontent.com/26063400/49137369-ec961180-f2f4-11e8-8673-99077cd847f6.png)

And this is what it looks like afterwards:

![image](https://user-images.githubusercontent.com/26063400/49137441-1a7b5600-f2f5-11e8-8c5e-dc2bf2f0c9bb.png)

How do I go about reading 12/8 timing? Any suggestions/explanations would be appreciated.

Thanks

**Comment by hbitteur** [comment] 2018-11-28 10:11
I'm afraid you fell in the hole of "non really supported time sigs".

First, OmrShape class is meant to prepare coming 6.0 for which we need training datasets (we thus have the ability from within current Audiveris 5.x to generate annotated datasets for 6.x). 
But current Audiveris 5.x only works with Shape class.

Second, although 12 and 8 are recognized time numbers, 12/8 is not a recognized time signature, therefore the OMR engine will not generate such signature even if it is able to recognize the individual numbers.
To add 12/8 as a legal signature, here is what you can do: In the Tools | Options menu, search for "optional" or directly navigate to AbstractTimeInter class. There is a constant named "optionalTimes" whose default value today is "6/4, 7/8". Simply modify this value to "6/4, 7/8, 12/8". Then restart Audiveris to really take the new value into account.

I don't have your input file, so I can't try it on my own. Could you share the input image?
Anyway, since I suspect this 12/8 to be a time modification within a staff, right after a double barline, (and not at the beginning of a staff), the OMR engine is less likely to recognize the time sig, because of the damages caused by the wrong detection of wholes notes.
To work around this, stop the engine at the end of HEADS step and manually remove these wrong whole notes. Doing so, the underlying pixels will remain available for recognition in SYMBOLS step.

If the engine recognition fails, then it's bad luck because you currently have no means to manually insert a brand new time signature into a system. You would have to resort to some external music editor working on Audiveris MusicXML output.

**Comment by WilloZA** [comment] 2018-11-28 11:08
Thank you for your response. Here is the input image I am using:
![purpose-2](https://user-images.githubusercontent.com/26063400/49147899-9cc44400-f30e-11e8-8a14-b7194142bf39.jpg)

**Comment by WilloZA** [comment] 2018-12-14 08:32
Does Audiveris support reading time signatures that are not at the beginning of the staff?

![image](https://user-images.githubusercontent.com/26063400/49992030-916a4d00-ff8b-11e8-9491-7c0b4f8b7e5e.png)

**Comment by hbitteur** [comment] 2023-07-01 19:43
The engine is now able to recognize time signatures any where.
Plus the end user can manually insert a time sig of any value.

Closing the issue.

**Closed by hbitteur** 2023-07-01 19:43 UTC
Labels: enhancement
