### ISSUE TITLE
Shifted noted in MusicXML output

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#163] opened 2018-05-16 17:40 UTC
Steps to reproduce:

Open [this score](https://github.com/Audiveris/audiveris/files/2010226/Bohemian.Rhapsody.zip) in audiveris, navigate to sheet #4 and transcribe it. In the first two bars in the upper system, correct the misrecognized "7" (TEXT) to EIGHT_REST as shown in red below:
![rhapsody corr](https://user-images.githubusercontent.com/6561800/40133451-1df220c4-5940-11e8-8aeb-b676ad02328d.png)

Now export this sheet as XML and import it in Musescore. The lower choral part contains shifted notes:

![rhapsody shifted notes](https://user-images.githubusercontent.com/6561800/40133588-887ea89a-5940-11e8-812b-4ba347d1b123.png)

**Comment by Bacchushlg** [comment] 2018-05-17 08:40
look at #133. There I had reported the same problem.
It always only appears for notes that are bounded.

**Comment by maximumspatium** [comment] 2018-05-17 11:32
Okay, let us mark this issue as duplicate of #133.

**Comment by hbitteur** [comment] 2018-05-18 16:13
@maximumspatium what tool do you use for such nice rectangular or round red annotations?
I use Windows Spinning tool which allows only hand-annotations (very shaky)

**Comment by maximumspatium** [comment] 2018-05-18 16:19
> what tool do you use for such nice rectangular or round red annotations?

This is the standard Image Viewer shipped with mac os x. It allows to place simple vectored graphics onto pictures of any kind...

**Comment by hbitteur** [comment] 2018-05-18 16:47
I have no Mac...
Anyway, I was able to reproduce the problem on your example. Stay tuned :-)

**Comment by Bacchushlg** [comment] 2018-05-19 09:55
Try to save the book (Ctrl-S), re-open and export again.
By hazard I found out that this seems to "solve" the problem.

**Comment by maximumspatium** [comment] 2018-05-19 10:05
> Try to save the book (Ctrl-S), re-open and export again.
By hazard I found out that this seems to "solve" the problem.

This sounds similar to the already resolved #118

**Comment by hbitteur** [comment] 2018-05-19 10:11
This is the reason why the problem sounded rather familiar to me.
Perhaps the fix was not complete.
I need more time for a real investigation. 

FYI, this weekend we are going to Le Mans for the french moto grand prix, and I don't carry my pc on the moto bike. Sorry :-) :-)

**Comment by maximumspatium** [comment] 2018-05-19 10:16
> This weekend we are going to Le Mans for the french moto grand prix,

That sounds like a lot of fun. Enjoy!

> and I don't carry my pc on the moto bike.

Why not? 😸

**Comment by hbitteur** [comment] 2018-05-21 14:21
Bug fixed in commit f1dacd55107acf665718a038207780f19886694f

FYI, the bug relates to the retrieval of step/octave values for some notes.
These are transient values (not persisted on disk) and are cached in note instances. In case of several retrievals for the same note, the cached values if any are returned, otherwise values are really computed from scratch.

This retrieval occurs in 3 parts of the code:

1. In CURVES step, when checking if a slur is in fact a tie. It was a mistake to perform a check so early, because measures were not yet populated with clefs (not even the header clef). By default a G_CLEF was used to compute step and octave.
2. In LINKS step, when re-checking if a slur is a tie (now that alteration and clef changes are known, and that measures are correctly populated). But any wrong computation of step/octave was still present in cache.
3. In score export, when exporting a note in MusicXML format.

This explains why only notes that were involved in tie slur checking, and that were located in measures governed by a clef different from G_CLEF, were impacted by the bug.
And the bug disappeared when saving/reloading the score, since the cache was reset.

Gasp, this took me a full day of investigation! :-)

**Closed** 2018-05-21 14:30 UTC
Labels: bug, duplicate
