### ISSUE TITLE
Can't delete with delete key

### ISSUE THREAD

**Issue by thescdoc** [Audiveris/audiveris#549] opened 2022-01-28 07:20 UTC
I've recently built 5.3 alpha and am unable to remove things from a scanned score by typing the Delete key. Running on a MacBook Pro. Is this a known problem? Have I missed something?I can select noteheads, rests, stems, and the like, and I can see the relationships between them.

Any help gratefully received.

 Here's the log file from when I ran the program.

[20220128T020444.log](https://github.com/Audiveris/audiveris/files/7956544/20220128T020444.log)
 

thanks

**Comment by hbitteur** [comment] 2022-01-28 09:30
> java.lang.IllegalAccessException: class org.audiveris.omr.ui.MacApplication cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @3c60b7e7

This is not a problem we had encountered yet.

But I suspect this is due to Java modular implementations imposing more and more constraints on access to internal services.
Perhaps we have now reached this breaking point with Java 17 on Mac, trying to access com.apple.eawt.Application

Googling on "cannot access class com.apple.eawt.application", I can see a bunch of posts. 
For example, in [https://bugs.openjdk.java.net/browse/JDK-8160437](https://bugs.openjdk.java.net/browse/JDK-8160437) I can read:
> To break encapsulation and access com.apple.eawt, existing application can set -XaddExports:java.desktop/com.apple.eawt=ALL-UNNAMED. That's an existing solution.

But this message was written in 2016, is this workaround still possible? Please try it on your own build, I personally have no access  (no pun intended!) to a Mac.

@maximumspatium : I'm afraid you are the only one in our small team able to address this topic! Could you give us a hand?

**Comment by maximumspatium** [comment] 2022-01-28 20:28
@thescdoc @hbitteur Sorry guys! I can't reproduce it. The delete key behaves as expected in my Mac Book Pro (OS X 10.13.6, Java 17).

**Comment by thescdoc** [comment] 2022-01-28 22:00
I'm using OS  X 10.15.7; I wonder if the difference is that 10.13.6 is from before Apple got so finicky about what's allowed to run.

If I can get my hands on a machine running 13, I'll try doing a build on it.

When I start Audiveris up, it says, "Unable to setup Mac OS X GUI integration" in the message pane at the bottom of the Audiveris window.

**Comment by maximumspatium** [comment] 2022-01-28 22:18
@thescdoc I'm getting the same error message when starting Audiveris in my Mac.
It's related to the old Apple EAWT classes that don't work properly with Java Runtime newer than 8.
Removing them is on my TODO list anyway. With some luck, it will fix your issue...

**Comment by maximumspatium** [comment] 2022-01-28 22:33
@thescdoc Sorry for the stupid question: does your keyboard have a **delete** or **backspace** key?
My keyboard comes with the backspace key. To delete something, I need to press both FN and Backspace keys.

**Comment by thescdoc** [comment] 2022-01-29 00:09
It's a MacBook Pro from late 2013 running Catalina 10.15.7

Key labeled "delete" in upper right next to += and right under the power and F12 keys. Lower left corner has key labeled "fn". Delete key removes character just left of cursor; fn+delete removes character just right of cursor; that was a setup option, and I don't remember what the other choice was. Tried both combinations in Audiveris; neither works for me.

**Comment by thescdoc** [comment] 2022-01-29 08:01
> To break encapsulation and access com.apple.eawt, existing application can set -XaddExports:java.desktop/com.apple.eawt=ALL-UNNAMED. That's an existing solution.
> 
According to this: https://dev.java/learn/circumventing-strong-encapsulation-with---add-exports-and---add-opens/
the current syntax for this is "--add-exports java.desktop/com.apple.eawt=ALL-UNNAMED" and it should work.

I did this in gradlew: 

DEFAULT_JVM_OPTS="--add-exports java.desktop/com.apple.eawt=ALL-UNNAMED"

It runs this command:  /Users/javauser/jdk-17.0.2.jdk/Contents/Home/bin/java --add-exports java.desktop/com.apple.eawt=ALL-UNNAMED -Xdock:name=Gradle -Xdock:icon=/Users/jimmy/audiveris/media/gradle.icns -Dorg.gradle.appname=gradlew -classpath /Users/jimmy/audiveris/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain run

It runs but still tells me "Unable to setup Mac OS X GUI integration" in the gui window, and I still have to delete things the hard way.

In the Terminal window it reports what seems to be the same IllegalAccessException twice:



Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
targetOS=macosx-x86_64

> Task :run
WARN  []              TesseractOCR 315  | Tesseract data could not be found. Try setting the TESSDATA_PREFIX environment variable to the parent folder of "tessdata".
INFO  []                      Main 401  | Environment:
- Audiveris:    5.3-alpha:74915af09
- OS:           Mac OS X 10.15.7
- Architecture: x86_64
- Java VM:      OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)         |
- OCR Engine:   No OCR is available!                                                      |
INFO  []                       CLI 269  | CLI args: []                                    |
INFO  []             AliasPatterns 131  | Alias patterns: [(IMSLP[0-9]*)-.*]              |
Mac OS X Adapter could not talk to EAWT:                                                  V
java.lang.IllegalAccessException: class org.jdesktop.application.utils.OSXAdapter cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @4dca0ecd
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.jdesktop.application.utils.OSXAdapter.setHandler(OSXAdapter.java:140)
        at org.jdesktop.application.utils.OSXAdapter.setQuitHandler(OSXAdapter.java:74)
        at org.jdesktop.application.Application.create(Application.java:257)
        at org.jdesktop.application.Application$1.run(Application.java:185)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO  []                   MainGui 415  | Audiveris version 5.3-alpha
INFO  []                   MainGui 416  | 
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No /Users/jimmy/Library/Application Support/AudiverisLtd/audiveris/logback.xml, skipped.
LogUtil. Configuration found file:///Users/jimmy/audiveris/res/logback.xml
LogUtil. Logging to /Users/jimmy/Library/AudiverisLtd/audiveris/log/20220129T021210.log

WARN  []                   MainGui 419  | No OCR is available! Check log file for more details.
INFO  []            PluginsManager 239  | No /Users/jimmy/Library/Application Support/AudiverisLtd/audiveris/plugins.xml file found
INFO  []           BasicClassifier 366  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 352  | Classifier data loaded from default uri file:///Users/jimmy/audiveris/res/basic-classifier.zip
WARN  []            MacApplication 192  | Unable to setup Mac OS X GUI integration
java.lang.IllegalAccessException: class org.audiveris.omr.ui.MacApplication cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @4dca0ecd
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at org.audiveris.omr.ui.MacApplication.setupMacMenus(MacApplication.java:148)
        at org.audiveris.omr.ui.MainGui.defineMenus(MainGui.java:594)
        at org.audiveris.omr.ui.MainGui.startup(MainGui.java:431)
        at org.jdesktop.application.Application$1.run(Application.java:187)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO  []                  Versions 392  | Versions. Poll frequency: Weekly, next poll on: 04-Feb-2022

BUILD SUCCESSFUL in 3m 3s
5 actionable tasks: 3 executed, 2 up-to-date
***@***.*** audiveris %

**Comment by thescdoc** [comment] 2022-01-31 20:57
The instructions here, https://audiveris.github.io/audiveris/_pages/install/sources/ <https://audiveris.github.io/audiveris/_pages/install/sources/>, give this "sudo port install tesseract-rus" as an example of installing the tesseract language files on OS X. When I did that it installed version 4, the wrong one, and apparently it installed a lot more than just the language files.

I went to the tesseract website and found the correct 3.04 versions of the language files. I'm not sure how safe it is to ask this way, but can somebody tell me where to put them?


thanks

**Comment by hbitteur** [comment] 2022-02-01 08:51
@thescdoc  A personal remark: It would be more efficient for the other people searching this forum if we could keep separate problems in separate issue reports.

Now, regarding this Tesseract topic: I'm afraid the instructions you found in this install section are out of date. We will have to fix this once for all, certainly by switching from Tesseract 3 to Tesseract 4 but running in the so-called legacy engine mode.

In fact you don't need to **install** Tesseract, whatever its version number, because the binary code is already in a library linked to Audiveris program.
Simply download the needed **3.04 language data files** (not the program) to some location on your machine, and then make sure that TESSDATA_PREFIX environment variable points to the **parent** folder of this location.

**Comment by maximumspatium** [comment] 2022-02-01 14:57
@thescdoc Did you solve the keyboard issue?

**Comment by thescdoc** [comment] 2022-02-01 16:39
> On Feb 1, 2022, at 9:57 AM, Maxim Poliakovski ***@***.***> wrote:
> 
> 
> @thescdoc <https://github.com/thescdoc> Did you solve the keyboard issue?
> 
I tried installing java 11 and building the release version. Same thing. Tried building on a couple of older laptops: 10.14 and 10.11. Same thing. I tried going back to java 8; couldn't build with that. Gave up and went back to java 17 and the development branch; it's got no more problems than anything else that I tried.

I tried plugging in a USB keyboard and using that, but it made no difference.

I tried a few of the two-letter keyboard shortcuts; they work fine, so it seems that the problem is just with the delete key. I have a hard time trying to imagine what's going on there. You think there's a chance I could find something in the source code? I looked a little and didn't find that. (In general, I'm just following the formulas that I can find without having the foggiest idea what's going on underneath. Never learned gradle either.) I do have considerable experience with java, but that was years ago. When this project came along, I found java 8 sitting on my machine and was more than a little surprised to find that we'd gotten to 17 in the meantime.

thanks

**Comment by thescdoc** [comment] 2022-02-01 16:51
> @thescdoc <https://github.com/thescdoc> A personal remark: It would be more efficient for the other people searching this forum if we could keep separate problems in separate issue reports.

Sorry, I don't understand  how addressing works on this mail group, so I just tried "Reply to All". It seemed to work, so I just kept doing that. Now that you mention it though, I reckon I could have thought to change the subject line. My bad.
> In fact you don't need to install Tesseract, whatever its version number, because the binary code is already in a library linked to Audiveris program.
> 
Yeah, I had seen that.
> Simply download the needed 3.04 language data files (not the program) to some location on your machine, and then make sure that TESSDATA_PREFIX environment variable points to the parent folder of this location.
> 
Yes, I have those but didn't know where they need to be. The TESSDATA_PREFIX env variable seemed to part of installing on Windows. I almost tried it anyway; guess I should have done that.

thanks

**Comment by hbitteur** [comment] 2022-02-01 16:56
> The TESSDATA_PREFIX env variable seemed to part of installing on Windows
I think it is not limited to Windows environment, it should work on Linux as well. I can't be positive for Mac though.

**Comment by thescdoc** [comment] 2022-02-01 18:21
> On Feb 1, 2022, at 11:57 AM, Hervé Bitteur ***@***.***> wrote:
> 
> 
> The TESSDATA_PREFIX env variable seemed to part of installing on Windows
> I think it is not limited to Windows environment, it should work on Linux as well. I can't be positive for Mac though.
> 

Yes, it seems to work on my Mac. If TESSDATA_PREFIX contains the name of the directory that holds the xyz.traineddata files it doesn't complain about OCR on startup..

**Comment by hbitteur** [comment] 2022-02-02 08:29
Fine, thanks!

**Comment by thescdoc** [comment] 2022-02-20 07:50
Problem fixed

I added a line to src/main/org/audiveris/omr/sig/ui/InterController.java to add an entry for the BACK_SPACE key to the InputMap. Now both backspace and delete keys work. (On my laptop, the delete key is faked by fn/backspace.)

An anomaly that I haven't figured out yet is that neither keystroke worked before, but now both do. Looking at the code, I'd expect the delete key to work before I changed anything, but it didn't. The whole project lost priority when the conductor removed the piece that I needed to work on from the program. Don't know when I'll get back to it.

While exploring the problem, I slipped a couple of logging lines into src/main/org/audiveris/omr/sheet/ui/SheetEditor.java. This had some interesting results but didn't change anything.

After reflecting on this for a while, I've come to the opinion that, while user editing is going on, the delete and backspace keys should have the same effect regardless of the computer system Audiveris is running on.

This file has what I hope is a more thorough description of what I did and what the results were.




IN src/main/org/audiveris/omr/sheet/ui/SheetEditor.java

    //~ Inner Classes ------------------------------------------------------------------------------
    //------------------//
    // SheetKeyListener //
    //------------------//
    /**
     * Listener in charge of retrieving the sequence of keys typed by the user.
     */
    public class SheetKeyListener
            extends KeyAdapter
    {

        /** First character typed, if any. */
        Character firstChar = null;

        @Override     // jbw debugging here     <================
        public void keyPressed (KeyEvent e)
        {
            logger.info("SheetEditor: {} saw character {}", "keyPressed", e.getKeyCode());
        }

        @Override
        public void keyTyped (KeyEvent e)
        {
            final char c = e.getKeyChar();

            logger.info("SheetEditor: {} saw character {}", "keyTyped", e.getKeyCode());     //jbw     <================



INFO  []               SheetEditor 507  | SheetEditor: keyPressed saw character 8      <=== typed backspace key
INFO  []               SheetEditor 515  | SheetEditor: keyTyped saw character 0
INFO  []               SheetEditor 507  | SheetEditor: keyPressed saw character 0      <=== held Fn down and
INFO  []               SheetEditor 507  | SheetEditor: keyPressed saw character 127         typed backspace which is delete with fn down
INFO  []               SheetEditor 515  | SheetEditor: keyTyped saw character 0

            keyTyped method sees only character code 0 with DELETE and BACK_SPACE keys.
            keyPressed method sees correct character codes (127 and 8) with those keys.

            This is interesting but didn't fix my problem.






              This is what fixed it.



IN src/main/org/audiveris/omr/sig/ui/InterController.java


    //----------------//
    // setSheetEditor //
    //----------------//
    /**
     * Late assignment of editor, to avoid circularities in elaboration, and to allow
     * handling of specific keys.
     *
     * @param sheetEditor the user pane
     */
    public void setSheetEditor (SheetEditor sheetEditor)
    {
        this.sheetEditor = sheetEditor;

        NestView sheetView = sheetEditor.getSheetView();
        InputMap inputMap = sheetView.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        // Support for delete & backspace keys
        inputMap.put(KeyStroke.getKeyStroke("DELETE"), "RemoveAction");

        inputMap.put(KeyStroke.getKeyStroke("BACK_SPACE"), "RemoveAction");    //   jbw     <=================  fixed my problem
        sheetView.getActionMap().put("RemoveAction", new RemoveAction());
    }

**Comment by hbitteur** [comment] 2022-02-23 09:45
@thescdoc 
Thanks for the support of  BACKSPACE key to remove an Inter.
I just pushed it in your name as commit 63747c78e5e6ce2723111874009a85d055fa9429
Closing the issue now.

**Closed by hbitteur** 2022-02-23 09:45 UTC

**Comment by thescdoc** [comment] 2023-01-22 18:33
Trying to build from development branch on a mid-2015 MacBook Pro running OS X 11.6.8 (Big Sur)
It ran 195 tests, failed one, ignored one.

Any ideas on what to do now much appreciated

Got this output on the terminal

***@***.*** audiveris % ./gradlew build      

> Configure project :
targetOS=macosx-x86_64

> Task :test

org.audiveris.omr.image.ChamferMatchingTest > testMatch STANDARD_OUT
    match
    12:58:01.236 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - TemplateFactory building all head templates for Bravura 56
    12:58:01.246 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - Building template for NOTEHEAD_BLACK Bravura 56
    12:58:01.255 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - OmrFont.createFont fontName: Bravura fileName: Bravura.otf
    12:58:01.465 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - Font url=file:/Users/jimmy/audiveris/res/Bravura.otf
    12:58:01.465 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - Found file Bravura.otf
    12:58:02.353 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - Created custom font java.awt.Font[family=Bravura,name=Bravura,style=plain,size=56] added:true
    12:58:02.404 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - NOTEHEAD_BLACK size:56 
    Template{NOTEHEAD_BLACK w:23,h:20 keyPoints:null
     slim:java.awt.Rectangle[x=3,y=3,width=16,height=14]}
    12:58:02.409 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - Building template for NOTEHEAD_VOID Bravura 56
    12:58:02.409 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - Using cached font Bravura 56
    12:58:02.411 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - NOTEHEAD_VOID size:56 
    Template{NOTEHEAD_VOID w:23,h:20 keyPoints:null
     slim:java.awt.Rectangle[x=3,y=3,width=16,height=14]}
    12:58:02.411 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - Building template for WHOLE_NOTE Bravura 56
    12:58:02.411 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - Using cached font Bravura 56
    12:58:02.413 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - WHOLE_NOTE size:56 
    Template{WHOLE_NOTE w:30,h:20 keyPoints:null
     slim:java.awt.Rectangle[x=3,y=3,width=23,height=14]}
    12:58:02.413 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - Building template for BREVE Bravura 56
    12:58:02.413 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - Using cached font Bravura 56
    12:58:02.414 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - BREVE size:56 
    Template{BREVE w:40,h:24 keyPoints:null
     slim:java.awt.Rectangle[x=3,y=3,width=33,height=18]}
    12:58:02.414 [Test worker] DEBUG org.audiveris.omr.image.TemplateFactory - Building template for NOTEHEAD_BLACK_SMALL Bravura 56
    12:58:02.414 [Test worker] DEBUG org.audiveris.omr.ui.symbol.OmrFont - Using cached font Bravura 56
    12:58:02.415 [Test worker] WARN org.audiveris.omr.ui.symbol.TemplateSymbol - no symbol in TemplateSymbol for NOTEHEAD_BLACK_SMALL in family Bravura

org.audiveris.omr.image.ChamferMatchingTest > testMatch FAILED
    java.lang.NullPointerException at ChamferMatchingTest.java:103


Found this here
file:///Users/jimmy/audiveris/build/reports/tests/test/index.html

Class org.audiveris.omr.image.ChamferMatchingTest
all <file:///Users/jimmy/audiveris/build/reports/tests/test/index.html> > org.audiveris.omr.image <file:///Users/jimmy/audiveris/build/reports/tests/test/packages/org.audiveris.omr.image.html> > ChamferMatchingTest
1
tests
1
failures
0
ignored
1.309s
duration
0%
successful
Failed tests
Tests
 <file:///Users/jimmy/audiveris/build/reports/tests/test/classes/org.audiveris.omr.image.ChamferMatchingTest.html#tab1>Standard output
 <file:///Users/jimmy/audiveris/build/reports/tests/test/classes/org.audiveris.omr.image.ChamferMatchingTest.html#tab2>
 <>testMatch

java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.ui.symbol.ShapeSymbol.getParams(org.audiveris.omr.ui.symbol.MusicFont)" because "symbol" is null
	at org.audiveris.omr.ui.symbol.TemplateSymbol.getParams(TemplateSymbol.java:110)
	at org.audiveris.omr.ui.symbol.TemplateSymbol.getParams(TemplateSymbol.java:44)
	at org.audiveris.omr.ui.symbol.ShapeSymbol.getDimension(ShapeSymbol.java:395)
	at org.audiveris.omr.image.TemplateFactory.buildTemplate(TemplateFactory.java:668)
	at org.audiveris.omr.image.TemplateFactory$Catalog.buildAllTemplates(TemplateFactory.java:945)
	at org.audiveris.omr.image.TemplateFactory$Catalog.<init>(TemplateFactory.java:917)
	at org.audiveris.omr.image.TemplateFactory.getCatalog(TemplateFactory.java:175)
	at org.audiveris.omr.image.ChamferMatchingTest.testMatch(ChamferMatchingTest.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

Wrap lines 
Generated by Gradle 7.3 <http://www.gradle.org/> at Jan 22, 2023, 12:18:18 PM

**Comment by thescdoc** [comment] 2023-01-22 19:10
I dug a little into TemplateSymbol.java.


It appears that line 92 --- ShapeSymbol symbol = font.getSymbol(shape); gets a null value for symbol.

Then the loop beginning on line 94 is skipped completely because there is no backup font.

Then the if statement beginning on line 103 executes and logs this:
WARN org.audiveris.omr.ui.symbol.TemplateSymbol - no symbol in TemplateSymbol for NOTEHEAD_BLACK_SMALL in family Bravura

And then it crashes at 110 when the null value is dereferenced.

**Comment by hbitteur** [comment] 2023-01-23 13:47
Thanks @thescdoc for reporting this bug.
It is now fixed in commit c0a15193ab4790905ed464a03e2e65414434675b I just pushed on development branch. Please pull.

However, you might have some difficulty in trying to explain what this bug has to do with the now-closed issue #549 ("Can't delete with delete key")... :-)
Next time, please create a _specific_ issue. It costs you nothing more and simplifies the life of all other people searching this forum.

**Comment by thescdoc** [comment] 2023-01-23 15:29
> However, you might have some difficulty in trying to explain what this bug has to do with the now-closed issue #549 <https://github.com/Audiveris/audiveris/issues/549> ("Can't delete with delete key")... :-)
> Next time, please create a specific issue. It costs you nothing more and simplifies the life of all other people searching this forum.
> 
Hmmmmm, evidently the mailing list did something that I can't see and wasn't expecting. Here's a screenshot from my "Sent" folder of the top of the mail I sent; there's no mention of issue #549 that I can see:



When I sent it, the subject line was "ChamferMatchingTest fails when building on BigSur 11.6.8". I thought I had created a new issue.

When you got it, the subject line was "Re: [Audiveris/audiveris] Can't delete with delete key (Issue #549)"? I can't explain that. Would love to fix this, but right now I'm mystified.

**Comment by hbitteur** [comment] 2023-01-23 15:35
Bad luck, the screenshot does not appear at all in your message above!
Therefore there is nothing to decide upon.
Never mind.
