### ISSUE TITLE
lot of miss-interpreted notes in good quality scan

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#112] opened 2018-03-07 13:15 UTC
![beatles - honey pie 1](https://user-images.githubusercontent.com/33522630/37094058-e14001f6-2211-11e8-9e42-68705767b061.jpg)

I'm a bit astonished about the many miss-interpreted notes in this scan. It appears to be of good quality.
Any idea about this?

**Comment by hbitteur** [comment] 2018-03-07 14:08
![image](https://user-images.githubusercontent.com/22053634/37095510-72e6e81e-2216-11e8-98a1-9bada1eff26e.png)
Here is the reason for this: In snapshot above, the various inters are listed by decreasing grade value. After the two ledger inters, the best graded inter is a (false) notehead black located between the ledgers. This head gets a grade of 0.606, just better than the two following ones (0.442 and 0.412) which are the correct blackheads, each centered on its ledger.

So this originates back to the template matching, which worked poorly here.
See below, the template results for the false head (0.606)
![image](https://user-images.githubusercontent.com/22053634/37096235-4d61da52-2218-11e8-8816-1c52e4d07cd7.png)
And the template results for the (correct) head (0.442)
![image](https://user-images.githubusercontent.com/22053634/37096313-909566e0-2218-11e8-9815-61b304af7ede.png)
My guess is that this score exhibits black heads and especially ledgers which are much larger than we would expect with this interline value. The green regions (ledgers and stems) do not count in the template evaluation, consider only the good pixel matches (shown as circles) and the bad pixel matches (shown as crosses).

**Comment by hbitteur** [comment] 2018-03-07 14:10
If you are interested in playing with these templates, just set the `displayTemplates` constant to true.
Then use mouse right click to position the template grid.

**Comment by hbitteur** [comment] 2018-03-07 15:10
I have played with size parameters a bit, always with the same input image, interline value of 22, and progressively increasing the size of the head templates. Here are the grade results for the top 3 heads ordered by their vertical position (remember, we have 3 candidates, which are respectively: true, false, true).
Standard size (22): 0.442, **0.606**, 0.412
Bigger size (22+1): 0.531, **0.592**, 0.512
Bigger size (22+2): 0.582, **0.597**, 0.524
Bigger size (22+3): 0.670, **0.549**, 0.570 <= correct results here, at last!

Here below are the heads (normal size, based on interline 22)
![image](https://user-images.githubusercontent.com/22053634/37099479-a5a82ad8-2220-11e8-8e25-46cabd27af7f.png)

Now, here below are the new heads (bigger size, based on interline 22+3) Notice the good size matching between the templates and the image pixels.
![image](https://user-images.githubusercontent.com/22053634/37099447-90f70d84-2220-11e8-948e-fedc060e3625.png)

**Comment by hbitteur** [comment] 2018-03-07 15:13
And the related template computation:
![image](https://user-images.githubusercontent.com/22053634/37100090-5a0d48c2-2222-11e8-98fd-ca595a818281.png)

**Comment by hbitteur** [comment] 2018-03-07 15:19
How could the engine estimate the most suitable size of a notehead? Before attempting to recognize them of course.
Today this is based simply on a musicfont scaled with the interline value. It works for most images but not for the one we have here.
Perhaps we could use a histogram of hote heads spots (they are today built as a side effect of beam spots in BEAMS step)

**Comment by maximumspatium** [comment] 2018-03-07 15:43
> So this originates back to the template matching, which worked poorly here.

I had several other scores where the template matching does a poor work. But this is mostly valid for void note heads.
Does Audiveris use template matching for all note heads including the black ones? I thought the black note heads are matched using mathematical morphology. I'm confused a bit...

**Comment by Bacchushlg** [comment] 2018-03-07 15:58
So, if I understand right, you "simply" need to calculate a mean value for the note heads in order to get a better value for template matching? Maybe you can provide a version with such an dynamic calculation, based on this mean value. Maybe it could also improve the recognition of the half notes (We should be able to expect that quarter and half notes have the same size!). I would give this a try with a couple of my scans to verify if it's a good idea.

**Comment by hbitteur** [comment] 2018-03-07 15:58
Template matching is used for all heads (void, black, whole) standard and cue sizes.
Morphology is used mainly for beams (closing) for symbols preparation (dilation) and for slurs (skeletons).
And neural network is used for all symbols except beams, stems and heads.

**Comment by hbitteur** [comment] 2018-03-07 16:06
We could analyze all the blobs of the head spots and consider only those whose bounds are "close" to the ones we pre-selected, based on interline value. Then select the most significant population as "the" representative ones, then derive template sizes.

This would work only for black heads (perhaps vertical stacks of 2 or 3 heads as well) but not for void heads (halves) because the voids don't result in usable blobs. We could extrapolate void size from black size.

**Comment by hbitteur** [comment] 2018-03-07 16:09
@maximumspatium When did you process these examples with poor results on void heads? Because I made improvements recently, specifically targetted to void heads.

**Comment by Bacchushlg** [comment] 2018-03-07 16:21
I just noticed that the templates for half notes are a bit bigger than the full ones (maybe 5%). Is this by design?

**Comment by hbitteur** [comment] 2018-03-07 16:29
Yes voids are bigger.
In the font currectly used by Audiveris (MusicalSymbols), a void head is already slightly bigger than a black head.
On top of that, I decided nearly a year ago to add an extra increase to void heads (+1), resulting in using 21 as interline for voids, when using 20 as interline for blacks. Results got better for void heads.

**Comment by Bacchushlg** [comment] 2018-03-07 16:31
Ok, I understand. I just noticed the difference and wanted to make clear that this is by design ;-))

**Comment by hbitteur** [comment] 2018-03-07 18:21
Here is what I can propose:
1. Today: Provide a manual hack to artificially increase heads template size (WRT interline value). For this, I simply provide an application constant that the user can modify on his own.
2. Later (5.2 release): Implement automatic on-the-fly template sizing as described in the posts above.

**Comment by maximumspatium** [comment] 2018-03-07 21:19
> When did you process these examples with poor results on void heads? Because I made improvements recently, specifically targetted to void heads.

I've tested it recently using this score:

![img-0176](https://user-images.githubusercontent.com/6561800/37113143-c8b40fd2-2244-11e8-8d79-b21a1a767d35.jpg)

I also noticed the following behavior: the default binarization parameters (mean = 0.7, stddev = 0.9) as well as global binarization provide the worst recognition. The result can be improved by setting the filter params to mean = 0.7, stddev = 0.3.

After playing around with different params I observed that the recognition of note heads
- seems to be sensitive to even very small pixel variations indistinguishable to the untrained eye
- tends to perform poorly for chords where note heads stick together

**Comment by maximumspatium** [comment] 2018-03-07 21:59
I've played with the template matching system for an improperly recognized chord from the above score:

![glyph 1807](https://user-images.githubusercontent.com/6561800/37120209-0fba8c52-225a-11e8-8503-ebac149d2cfb.png)

![glyph 1807 templ1](https://user-images.githubusercontent.com/6561800/37120224-164d8bf0-225a-11e8-85d6-86d39b9371b6.png)
![glyph 1807 templ2](https://user-images.githubusercontent.com/6561800/37120225-167866b8-225a-11e8-8a56-5124b6777802.png)
![glyph 1807 templ3](https://user-images.githubusercontent.com/6561800/37120227-16a0d2ec-225a-11e8-8e45-c9e64e6b9362.png)

As you can see in the pictures above, template matching reports the best matching grade of 0.572 for the position between two ledgers - that's what our human perception system would clearly reject. The true note head positions on the ledger lines got lower grades (0.571 and 0.555 respectively)...

**Comment by Bacchushlg** [comment] 2018-03-08 08:27
If I may propose a little helper: if you already now calculate the head size mean value (as you had proposed before) and output it in the output window, together with the one derived from the interline value? This could help "us" to calculate a good value for the manual hack (and will also help on the way to the final solution).

**Comment by Bacchushlg** [comment] 2018-03-08 09:46
About the analysis of @maximumspatium : is it possible that we should have different templates for heads on a lines and between lines? The template of a note head on a line could then consist of two half elipses leaving the middle (the space of the ledger line) free?

**Comment by hbitteur** [comment] 2018-03-08 10:40
Thank you Maxim for this "erase or not erase" a lot! This sounds like a good definition of OMR :-)

I'd suggest that we don't spend too much time on this template matching. First because I tried many approaches in the past, including the templates with and without ledger, and second, because we are likely to through away all this when we switch to patch or system classifiers (I just received trained material from ZHAW and I will make some early tests with it).
So let's focus on what sounds reasonable in the short term.

Templates must be properly scaled. We have an interesting possibility based on the head spots, this would lead to templates based on the actual image spots, all shapes would benefit from this, namely black and void heads. Especially the "inter-ledger" match would no longer be the best match. I will commit today a version with a manual way to artifically modify the template scales, so that Maxim can re-apply his templates (which were a bit too small).

Recognition of void heads is not that bad, but it is fragile, and depends on how the void heads appear in the image at hand. In these examples with bad results we are discussing about, we can notice that the void heads are in fact very similar to black heads, in other words the internal white hole is smaller than usual, and specifically smaller than the hole defined by the music font Audiveris uses, see below:

![image](https://user-images.githubusercontent.com/22053634/37145526-62bde6a8-22c1-11e8-978b-2a7e12d6ee6e.png)

Example of "fat" void head, about the same scale, below:
![image](https://user-images.githubusercontent.com/22053634/37145824-42c96b32-22c2-11e8-9873-c1b0a13efcb3.png)
Another example, even worse, with the "invasion" of ledger:
![image](https://user-images.githubusercontent.com/22053634/37145983-c4b32854-22c2-11e8-90eb-689de52ad150.png)
This last example should convince us that we'll never be able to provide templates with this thickness of ledger, and so it is safer to consider ledgers, lines and stems as "neutralized" regions (this is current Audiveris strategy).

The point with this concrete image example, is to show very clearly how the internal white areas (holes) may get very tiny, much smaller than the font-based templates. It is not a surprise if these examples are mistaken for black heads!
By the way, I tried to assign higher weights to template hole locations, this resulted in nearly every location inside staves being recognized as a void head! And this is a lot of locations...

So, as a last attempt, why not accepting the fact that such nearly-black void heads are taken as black heads in a first phase. Then a second phase could inspect (using whatever means) each of these "black candidates" to look for some white region in them, and re-assign them to void. Not very elegant I agree, but it may just work.

**Comment by maximumspatium** [comment] 2018-03-08 12:39
> So, as a last attempt, why not accepting the fact that such nearly-black void heads are taken as black heads in a first phase. Then a second phase could inspect (using whatever means) each of these "black candidates" to look for some white region in them, and re-assign them to void. Not very elegant I agree, but it may just work.

That sounds similar to an earlier proposal of mine. 2015 I expressed the idea to fill objects with holes using morphology and then to treat them all as black note heads. In the case a match is found, the information about holes will be reconsidered.

Your proposal seems to be more elegant. The question is how to detect "holes". What do you think of?

**Comment by hbitteur** [comment] 2018-03-08 15:18
Sorry Maxim, I didn't remember of this proposal, but great minds think alike :-)
The problem is of course to detect the holes.
If we try to do this with morphology, before candidate heads are retrieved, I'm afraid it's almost impossible to detect the right holes and only those ones.

But, if we have the result of the first phase (right and false black heads, perhaps some void heads as well), then we can limit the processing precisely to the black head candidates.
We can use the voidHead template over a blackHead candidate, this will give us the precise hole locations where pixels "should" be white. Then a quick reading of the actual pixels at these locations will give us the actual amount of white pixels "in the hole". And with a suitable minimum threshold, we could say whether it's a void head or a black head.

Here below is a magnified vue of a the void head template for interline 21. If you are interested, you can get the generated templates by setting the constant `keepTemplates` to true in class ShapeDescriptor, they will be written to the `temp` folder of your own Audiveris folder.

- Cells in black are the expected foreground locations
- Cells in red are the expected exterior background locations (with their chamfer distance to foreground)
- Cells in pink are the expected interior background locations (they have their chamfer distance coded with a negative value)
Chamfer distance values should be divided by 3 to get the exact value, but here we care only about the sign of the distance.

![notehead_void tpl21](https://user-images.githubusercontent.com/22053634/37157959-77106ecc-22ea-11e8-8ffc-97d4ec9800a1.png)

**Comment by hbitteur** [comment] 2018-03-08 15:59
I just pushed commit 3d8ede51397e39d29ada1bb0999ea47c2e5697c7 which allows the user to manually modify the template sizes. This is done via constants in MusicFont class, and the application needs to be restarted to update the catalog of templates.

There are 2 constants the use can play with in MusicFont:
1. `globalExtent` (default 1) which is applied to all template shapes (black, void, whole and their cue cousins). In fact, this value has been present for several months, I just had forgotten about it.
2. `additionalVoidExtent` (default 1) which is applied specifically on void heads (in addition to the global extent value).

So, by default, an image with interline value of say 20, will play with (black, whole) templates based on 21 and (void) template based on 22. Smaller values (2/3) for cues.

And for the precise example we were discussing about, simply set the `globalExtent` to 4. This will use (black, whole) templates based on 24 and (void) template on 25. I'm not sure we need, still for the example at hand, to keep the `additionalVoidExtent` to 1, 0 should be OK.

Don't forget to unset these modifications when processing other (more standard) score images. This is the downside of this temporary hack. :-(

**Comment by Bacchushlg** [comment] 2018-03-08 16:40
I just tried this version. I get the best result with globalExtent = 2, with 4 almost all half notes get detected as quarter. additionalVoidExtent is set to 0.
I have the slight impression that the void note heads are a little "special" and that this is the reason for the rather bad recognition. Still for 2 chords in the last system same half notes are not correctly recognized.
But on the whole this works now much better than initially.

**Comment by maximumspatium** [comment] 2018-03-09 23:22
Unfortunately, I wasn't able to improve the recognition of black note heads by adjusting the `globalExtent` in my case (Bohemian Rhapsody). When globalExtent >= 4, even fewer heads will be recognized.
As opposite, increasing `additionalVoidExtent` leads to many false positives...

**Comment by hbitteur** [comment] 2018-03-22 22:14
I implemented the re-evaluation of black heads as void heads (based on white pixels in template hole) in commit 961f56840f0b40bcf89b158ddf85a4b509284495
I applied it on the example of #83 case, with a globalExtent manually set to 3 instead of 1 to get better templates. All the void heads got correctly recognized as well as all the true black heads.
Could you give it a try on other examples and share your results?

The next action would be to automatically determine the best template sizing (rather than manually setting it). I may implement this sooner than I planned, since it might conclude the main template matching problems.

**Comment by Bacchushlg** [comment] 2018-03-23 09:31
I tried with a couple of scans, and it works much better now. Those few cases where there is still a faulty detection are ok from my point of view. I get a rather fluent workflow now :-))

**Comment by hbitteur** [comment] 2018-03-29 10:02
In commit 863a02e175f50e446811d0d3c640d03bf3a91d2e, I finally implemented the automatic sizing of heads, based on the analysis of black head spots.
If the rare case where the analysis fails, for example because there are too few black heads in sheet, the program falls back to using a "head ratio" which is applied to music font. Default value for `headRatio` constant is 1.1 which says that font for heads should be 10% bigger than for non-head symbols.

There is no more `globalExtent` and `additionalVoidExtent` constants, because I think they are no longer mandatory.

Enough of these template-based head detection developments! Next "revolution" will be the use of the patch classifier which should outdate all these font tricks.

**Comment by hbitteur** [comment] 2018-03-30 07:52
Closing this issue

**Closed by hbitteur** 2018-03-30 07:52 UTC
Labels: enhancement
