### ISSUE TITLE
Octaviation

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#448] opened 2020-12-12 20:48 UTC
Doesn't Audiveris recognize the symbol of "octave up"?  thanks

**Comment by hbitteur** [comment] 2020-12-13 17:04
You have the ability to set the octave shift at clef level for G clef and for F clef. It's like a standard clef symbol with a small "8" just above or below the clef.

But I think you are referring to isolated OTTAVA_ALTA (symbol like 8va) and OTTAVA_BASSA (symbol like 8vb). These symbols can be recognized by current engine or manually assigned by the end-user.

However, they are not fully handled because these symbols only mark the starting point of the octave shift.
The range is often indicated by a sequence of horizontal dashes, ending with a small vertical leg. And both the dashes and the small leg cannot be reliably detected by the engine. That's today's reality.

We could think of a way for the end-user to manually indicate where the octave shift actually stops. I think I remember that the shift should stop at the end of the current system, but I'm not sure at all if this is the rule and if music writers comply with it.
We need a way to explicitly tell Audiveris where a given octave shift precisely stops. Could you help me on this?

**Comment by rodolfo-medina** [comment] 2020-12-13 20:24
On p.3 of the attached score you have such an "ottava alta".  It doesn't stop at the end of the system but continues over 4 systems.  How can I assign that in Audiveris?  And yes, of course, I'd love to, how can I help you on explicitly telling Audiveris where a given octave shift stops?

[schubert-sonata18d894-primo_tempo.pdf](https://github.com/Audiveris/audiveris/files/5685373/schubert-sonata18d894-primo_tempo.pdf)

**Comment by hbitteur** [comment] 2022-09-03 19:51
#448 is still on the todo list and not yet implemented even in 5.3 on development branch.
I confess I'm working on other topics, mainly an SSD network that would bring all recognized musical symbols in one shot. A daunting task.

I will try to to provide you with an implementation that at least let you define where octaviation starts and stops, so that everything can get correctly exported in MusicXML.
ETA: a couple of weeks.

Sorry for this.

**Comment by rodolfo-medina** [comment] 2022-09-03 19:56
Thanks indeed for all you're doing and you've done in creating this marvellous tool.

**Comment by hbitteur** [comment] 2022-09-05 12:40
@rodolfo-medina 
Octaviation is supposed to start with an "8va" or "8vb" symbol, for ottava alta and ottava bassa respectively. And similarly for 15 and 22 values.

In your provided Schubert example, we just have an "8" symbol.
First question:
- How do we know if it's an alta or a bassa shift?

Second question: How can we determine the impacted staff? 
- the staff below for an alta?
- the staff above for a bassa? 
- the closest staff?

I'm searching the Internet for answers, but please help me if you can.

**Comment by rodolfo-medina** [comment] 2022-09-06 15:01
What do you mean by 15 and 22 values?  The impacted staff is the closest one.  If the "8" or "8va" is above the staff, you have an ottava alta; if below you have an ottava bassa.  How can I assign that in Audiveris?

Thanks

**Comment by hbitteur** [comment] 2022-09-06 15:26
**8va/8vb** (ottava alta/bassa) is for 1 octave shift
**15ma/15mb** (quindicesima alta/bassa) for 2 octaves shift
See the 'size' attribute in [MusicXML octave-shift element](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/octave-shift/), which also accepts 22 for 3 octaves shift!!!

So, if I understand your answer correctly, an "8" symbol (without va or vb suffix) means 8va by default. Could you confirm?

Vertical distance is not reliable enough to assign a symbol to its "related" staff, unfortunately.
But, if we assume that 8=8va, then we know that the related staff is:
- the staff just below for 8/8va and 15ma
- the staff just above for 8vb and 15mb.

**Comment by rodolfo-medina** [comment] 2022-09-06 15:30
Yes, for me it is as you say, I confirm.

**Comment by hbitteur** [comment] 2022-09-07 13:54
Correction, symbol "8" alone means ottava but does not imply ottava alta (nor ottava bassa either).
It indicates only a 1-octave shift.

But in which direction?
- If located above (key or staff) then it means ottava alta,
- If located below (key of staff) then it means ottava bassa.

Unfortunately we are on our own to determine which precise staff is the related staff when dealing with a system of several staves.
- Vertical distance is a poor indicator.
- The ending sign (the small vertical leg that ends the dash line), when present and well detected, points back to the related staff.

**Comment by rodolfo-medina** [comment] 2022-09-07 15:45
We can invent some symbol to tell Audiveris which stave the "8" belongs to and what the starting and ending points of octaviation respectively are...

**Comment by hbitteur** [comment] 2022-09-07 15:53
Yes, we will add the  "8" shape (on par with "8va" and "8vb").
Then, if it horizontally overlaps a clef, then it's a clef-octave-change, otherwise it's an octave-shift.
If the user needs to manually determine the target staff, dragging the octave symbol to the target key or first chord will transitively designate the target staff.

The problem is with the ending point, I have no clear shape candidate. It should look like a small vertical (dashed?) line.

**Comment by rodolfo-medina** [comment] 2022-09-07 15:56
It may be anything, some nice symbol one...

**Comment by RensBloom** [comment] 2022-09-11 09:25
For the ending point, would it be possible to make a shape candidate that includes the corner ┑or ┙?

I agree that vertical distance to the staff would be a really poor candidate. The vertical distance from the horizontal line to anything else linked to a staff (note, accents, remarks, slurs) might be a better candidate to distinguish between ottava alta or ottava bassa. In some books I see that the the line is even between the notes and fingering, or between the notes and a pedal indication.

Be aware that 8vb is often written as 8va bassa.
Sometimes the horizontal line starts at the bottom of the 8 symbol when it is an ottava bassa and at the top of the 8 symbol when it is an ottava alta. Though, counterexamples do exist.
I have [one example on IMSLP](https://s9.imslp.org/files/imglnks/usimg/f/f1/IMSLP05080-Liszt_-_S244_Hungarian_Rhapsody_No15_(edition_b).PDF) that might be good training data, as it includes different notations throughout the score, even an example where the horizontal line is a bit curved.

**Comment by hbitteur** [comment] 2022-09-13 19:36
I'm away from home until end of this week.
I'll get back to you.

Le dim. 11 sept. 2022 à 11:25, RensBloom ***@***.***> a
écrit :

**Comment by hbitteur** [comment] 2022-09-20 10:16
My priority is to come up with a data model and an implementation that allows the end user to manually handle octaviation (today there is just nothing available in Audiveris):
This means the ability to assign or drag n' drop an ottava sign and then manually edit it if needed (to locate it above or below the related staff, to extend it horizontally, etc) and finally to have this information exported to MusicXML.
This development is on good tracks.

Once this is done, we will investigate how much we could automate Audiveris recognition of ottava lines. I'm less confident on this part, because of several difficulties:
- Initial sign. We can have different signs: 8, 8va, 8vb, 8va bassa, ...
- Dotted/dashed line. There is yet no algorithm in Audiveris code to detect a dotted or dashed rather horizontal line.
- Final optional leg. Rather similar to problem above.
- Detection of the related staff. I especially appreciate the stair-looking "line" at bottom of page 2 in @RensBloom example :-)

**Comment by rodolfo-medina** [comment] 2022-09-20 11:35
The simple possibility of assigning it is already great.

**Comment by hbitteur** [comment] 2022-09-26 14:16
I just pushed commit 2f65e3185b7b728ef5f783c67decd749cbd16f3a on "development" branch
This is a partial support for octaviation:
- Manual handling is OK. 
- Automatic handling is still rudimentary, but you can always manually fix it.

The ShapeBoard now provides a ClefsAndShifts family, with shapes for Ottava, Quindicesima and Ventiduesima as follows:
![image](https://user-images.githubusercontent.com/22053634/192289343-1d74d37a-4f11-4007-9687-73f393c4ac17.png)

The easiest approach is to drag the octave shift or your choice to its target location in the score. The related staff is sticky, and depending on the current location with respect to the staff, the octave shift switches between ALTA and BASSA kind, together with the direction of its end hook.
Release the item when you are satisfied with the location. 
![image](https://user-images.githubusercontent.com/22053634/192298637-80636628-6e6b-4eb8-bc7d-568a2548b0b0.png)

Then enter edition mode via a double click on the just dropped item, and use the right handle to extend the octave line until the desired end. 
![image](https://user-images.githubusercontent.com/22053634/192299121-bd538714-61ef-41fe-91f3-bfb8b77c2b31.png)
That's it.

Another approach is to manually assign an existing octave shift glyph.
Pay attention to limit the glyph to the number part (8, 15 or 22) without the following dashes.
In this approach, you will be prompted for the target staff (which in turn will determine kind and hook end)

Note that in this implementation, we rely on the following assumptions:
- Every octave shift exhibits a hook end,
- Kind (alta/bassa) is determined by item location WRT staff.

Please try out  and provide feedback on this first implementation.

To further ease the manual insertion of a multi-system octaviation line, I'm thinking of allowing the end-user to drag the right handle of the octave shift several systems down. At handle release time, Audiveris would create several octave shifts lines, one per system. This sounds doable and would certainly be more convenient than to manually create one line per system.

And of course, the problem of automatically and reliably determining the target staff is still open. Please help me!

**Comment by hbitteur** [comment] 2022-10-13 18:10
> To further ease the manual insertion of a multi-system octaviation line, I'm thinking of allowing the end-user to drag the right handle of the octave shift several systems down. At handle release time, Audiveris would create several octave shift lines, one per system. This sounds doable and would certainly be more convenient than to manually create one line per system.

I'm happy to tell you that this editing feature is now available with commit 4bb9e25b587cac0832c55a67fdd0baeb28b3ca54
A great moment of bravery with this editor! :-)

The handbook is still to be updated for these octave shifts.
Meanwhile, you can try this feature on your own: pull a side handle of an octave shift until the corresponding staff above or below (in the same sheet) and you will see the octave shift extend into a multi-staff logical octave shift, which can be further extended or shrunk.

**Comment by rodolfo-medina** [comment] 2022-10-15 07:47
Thank you.  In order to try it, I did:

 $ git checkout development
 $ ./gradlew clean build

but got error:

---------------------------------------------------------------------------------------------------------------
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
targetOS=linux-x86_64

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
5 actionable tasks: 5 executed
---------------------------------------------------------------------------------------------------------------

Could you please help me?

Thanks,

Rodolfo

**Comment by hbitteur** [comment] 2022-10-15 11:26
@rodolfo-medina 
Reading "invalid source release: 17", perhaps you have not installed or are not using Java 17
Could you check?

**Comment by hbitteur** [comment] 2022-10-15 11:28
I just pushed a chapter dedicated to Octave Shift handling in Audiveris handbook.
You can read it [here](https://audiveris.github.io/audiveris/_pages/ui_tools/octave_shift/).

**Comment by rodolfo-medina** [comment] 2022-10-17 14:36
Works fine for me.  Thanks!!

**Comment by hbitteur** [comment] 2022-10-17 14:37
So, this was a problem with Java version?

**Comment by rodolfo-medina** [comment] 2022-10-17 14:43
It seems it was, because I installed openjdk-17-jdk in my Debian system and then I could enter the development branch.

**Comment by hbitteur** [comment] 2023-06-30 09:51
Audiveris 5.3 was just released with fulll support for these octave shifts.
So, I'm closing this issue now.

**Closed by hbitteur** 2023-06-30 09:51 UTC
Labels: Octaviation
