### ISSUE TITLE
Duplication of every tone in MXL export

### ISSUE THREAD

**Issue by ossk** [Audiveris/audiveris#465] opened 2021-02-01 18:04 UTC
In the example sheet automatic sheet processing fails at the "Chords" step initially but manual stepping works then. When exporting the result, every tone appears twice in the resulting MXL file. I found no way to remove or avoid this duplication.

![Schumann_example_top](https://user-images.githubusercontent.com/3596270/106498374-8e11e280-64bf-11eb-8ddb-2535925d8a56.png)

Config:
INFO  []                      Main 399  | Environment:
- Audiveris:    5.2.1-alpha:1c17a38a3
- OS:           Linux 4.15.0-135-generic
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 237  | CLI args: []
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                   MainGui 425  | Audiveris version 5.2.1-alpha
INFO  []                   MainGui 426  | 

The error at the "chords" step is:
WARN  [Schumann_example_top]                 SheetStub 918  | Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -4 out of bounds for length 392
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -4 out of bounds for length 392

The OMR and MXL files are attached in zip.

[Schumann_example_top.zip](https://github.com/Audiveris/audiveris/files/5905745/Schumann_example_top.zip)

**Comment by hbitteur** [comment] 2021-02-02 10:50
The root cause for this runtime exception was found in STEMS, where a stem got wrongly linked to a nearby beam.
![image](https://user-images.githubusercontent.com/22053634/106585111-446cda80-6547-11eb-8502-840396870d07.png)
The input image is very crowded, resulting in beams and stems very close to one another. Although they are unrelated, the stem end is so close to the beam that they get connected by the OMR engine.
See the green lines from the selected beam, some of them go up to the two upper stems, while they should not because the upper beam and the lower beam belong to separate beam groups.

This case will no longer occur in the coming Audiveris version (5.2) which is still being worked upon.

But for the version at hand (5.1), the OMR engine uses a very "greedy" approach when trying to link stems and beams. In the configuration high-lighted by the red circle in the picture above, vertical gap between stem and beam is just 3 pixels, which means 0.167 interline since your score scale is 18 pixels per staff interline.
By default, the maximum vertical gap between a beam and a stem (constant yGapMax in BeamStemRelation class) is set to 0.8 (18 * 0.8 =  14.4 pixels), way above your tiny gap of 3 pixels.

As a workaround for the case at hand, you can simply modify this application constant. Use menu Tools | Options, then type BeamStemRelation in the search field. And manually modify yGapMax from 0.8 to say 0.15 value.
Needless to say that this modification should be temporary, just to transcribe this score.

FYI, user modifications persist between Audiveris runs when done in interactive mode but not when done in batch mode.
Therefore, it might be more convenient to do this in batch mode, with CLI options as follows:
>-batch
>-option org.audiveris.omr.sig.relation.BeamStemRelation.yGapMax=0.15

**Comment by hbitteur** [comment] 2021-08-06 08:10
Tested with recent 5.2.3, OK
Closing

**Closed by hbitteur** 2021-08-06 08:10 UTC
