### ISSUE TITLE
Help with Schumann's Kreisleriana n.8

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#430] opened 2020-11-04 08:36 UTC
Schumann wants here a 2/4 tempo in left hand but, in right hand, still a 6/8.  This could be achieved with triplets in the right hand which involve a group formed by a 1/8 note, a 1/16 rest, a 1/16 note and a 1/8 note.  How to tell Audiveris recognize such triplets, if possible...?  I don't manage to.  thanks...

**Comment by rodolfo-medina** [comment] 2020-11-04 08:38
I'm trying to attach image,,,

**Comment by rodolfo-medina** [comment] 2020-11-04 08:39
.

**Comment by hbitteur** [comment] 2020-11-04 08:39
yes, an image would help! :-)

**Comment by rodolfo-medina** [comment] 2020-11-04 08:40
I don't manage to attach image, strange, sorry...

**Comment by rodolfo-medina** [comment] 2020-11-04 08:46
nothing, I don't manage to attach image...  why??

**Comment by rodolfo-medina** [comment] 2020-11-04 08:51
hbitteur, could I send it to you via email, and you attach it then...?  thanks...

**Comment by rodolfo-medina** [comment] 2020-11-04 09:13
.here's the image:

![screenshot 2020-11-04 08:20:13](https://user-images.githubusercontent.com/64352612/98091908-eebc5f80-1e7d-11eb-9351-43a8495c1ac8.png)

**Comment by hbitteur** [comment] 2020-11-04 09:59
What a mess!

Basically, the measure is 2/4, horizontally divided in 1/4 then 1/4 (the 2 halves are very similar).
I don't take left hand vs right hand into consideration, the two staves are part of the same measure.

So, each half is a sequence of:
1. 1/8 head
2. 1/16 rest
3. 1/16 head
4. 1/8 head

This sums up to 3/8 to be squeezed into one 1/4.
Could you try to manually drag n' drop a tuplet (3 or 6)  to a location above these notes.
It may catch up a few notes automatically if the tuplet is close enough to the notes.
If some links "tuplet - note" are missing, try to manually add them, simply by pointing and dragging from the tuplet to the note (head or rest), or vice versa.
When you click on the tuplet sign, it displays its related links as green segments.

Do this for both halves of the measure. It should turn white.

**Comment by hbitteur** [comment] 2020-11-04 10:11
On a second thought, we may have a problem with the right side of the measure.
Because the last chord of lower staff is perfectly aligned with the 1/16 chord of the upper staff, and by introducing a tuplet, these 2 chords should no longer belong to the same time slot.

To fix that, you could force Audiveris to use separate time slots for these 2 chords.
Select (one note of) lower chord and (one note of) upper chord, and use a right click to open the popup contextual menu. It should offer you a "Chords" submenu, with the ability to force separate time slots.

This feature is part of the coming 5.2 version, not yet released. Pull and build the "development" branch to get it. 
Preliminary documentation is in 5.2 handbook available on [https://audiveris.github.io/audiveris/](https://audiveris.github.io/audiveris/).

**Comment by rodolfo-medina** [comment] 2020-11-04 15:13
It seems to me rather that the two chords (last of lower staff and 1/16 of upper staff) actually *should* belong to the same time slot just *because* of the triplet up there, which is prefectly split into two halves by the beam down there on the left hand: the first half of the triplet is 1/8 head + 1/16 rest, and the second half is 1/16 head + 1/8 head...  the last chord of lower staff occurs just in the middle of the triplet above i.e. at the end of the first half of the triplet i.e. just where it is now in the picture, so it just remains there as its right place...  Am I wrong?

**Comment by rodolfo-medina** [comment] 2020-11-04 15:14
...just the same way as 3/2 = 1.5...

**Comment by hbitteur** [comment] 2020-11-04 16:14
Let's make the computation, starting from half of the measure (1/2 offset from measure start, but we don't care, so let's count from 0).

Upper staff (4 notes, with a tuplet);
1. Offset 0, head duration 1/8. With tuplet effect, this duration becomes 1/8 * 2/3 = 1/12
2. Offset 1/12, rest duration 1/16. With tuplet: 1/16 * 2/3 = 1/24
3. Offset 1/12 + 1/24 = **1/8** , head duration 1/16. With tuplet: 1/24
4. Offset 1/6, head duration 1/8. With tuplet: 1/12
total duration: 1/4

Lower staff (2 notes, no tuplet):
1. Offset 0, first head, duration 1/8
2. Offset **1/8**, second head, duration 1/8 
total duration: 1/4

Conclusion: at the same offset 1/8 from measure half, we can find the two vertically aligned notes.
So, you are right, and there is no need to twist slot policy (provided of course that a tuplet is inserted for each half of upper measure).

**Comment by rodolfo-medina** [comment] 2020-11-04 16:43
Fine!  Now comes the battle for settling one triplet for each half of upper staff: two triplets all together.  As you said, I managed to link the triplet symbol `3' to the four notes, in both halves: in fact, clicking on `3', the four links are displayed as shown in the picture.  Nevertheless, the whole measure remains red and also Musescore does not seem to correctly `understand' the situation.  I'm attaching the PDF source as well.  It's measure 26.  Thanks...!

![screenshot 2020-11-04 16:32:39](https://user-images.githubusercontent.com/64352612/98139562-411c7100-1ebc-11eb-9c71-cc0d82494c2b.png)

[musicalion78372-1.pdf](https://github.com/Audiveris/audiveris/files/5489151/musicalion78372-1.pdf)

**Comment by hbitteur** [comment] 2020-11-05 09:07
There is a problem in the OMR engine. The 1/16 rest is not properly taken into account.

I remember that rests "physically embedded" into a beam and its chords are correctly supported, but in the case at hand the chords that surround the rest are in opposite directions with respect to the beam.

This might be the root cause. I will need to double-check the algorithm but yesterday night I couldn't remember where in the code the logic is implemented. I'll search again this morning.

Stay tuned... :-)

**Comment by hbitteur** [comment] 2020-11-05 10:23
I found it, and indeed the logic to detect "interleaved" rest between two beamed chords is based on the polygonal area delimited by the 2 chords.
This works for chords in the same direction, because the area is a rectangle for horizontal beams and a parallelogram for slanted beams.
But when the 2 chords are in opposite directions, this area is so much reduced that the rest symbol does not intersect this area.

How should we determine the lookup area in this case? With the constraint to avoid catching irrelevant rests.
I'd suggest to focus on the right-hand chord, because this is the most concerned by the rest (in the mind of the person who plays the score).
So the area will be a parallelogram determined by the right-hand chord and the beam segment between the two chords.
In our example, this will mean a rectangle above the beam.

![image](https://user-images.githubusercontent.com/22053634/98228642-23511980-1f59-11eb-9f93-5375b02b7367.png)

**Comment by hbitteur** [comment] 2020-11-05 10:29
Beside this improvement in the OMR engine, perhaps we should provide a way for the user to interactively tell the engine that a given rest should be considered as interleaved in a given beam.

To be investigated.

**Comment by rodolfo-medina** [comment] 2020-11-05 15:47
A workaround could be to move all the right hand stuff to the upper staff...  I'm working this way now and it seems to work...

![screenshot 2020-11-05 15:45:56](https://user-images.githubusercontent.com/64352612/98262955-1bf03700-1f7e-11eb-9fcb-9ee87315a0f4.png)

**Comment by rodolfo-medina** [comment] 2020-11-05 15:48
(...why do those triplet symbols remain red, and also the beam bottom...?)

**Comment by hbitteur** [comment] 2020-11-05 16:29
An Inter instance turns red when it is detected as being in some abnormal status.
- For a beam, it needs a chord connected on left side and a chord connected on right side. In you example, the beam in red has no connected chord on its right side.
- For a tuplet (3 or 6), it is more complex, and too strict I think: it needs to have exactly 3 or 6 chords connected, and in the case of 2-staff measures these chords are counted only in the staff of the left-most chord. But don't worry too much , because for manual items the abnormal "status" has no concrete impact, it is meant only for user visual check.

**Comment by hbitteur** [comment] 2020-11-06 11:27
News from the front: the triplets are still colored in red, but the measures are now OK.
![image](https://user-images.githubusercontent.com/22053634/98359730-f409dd80-2028-11eb-9163-a7cd1abdb0b2.png)
You can check the time slots in the picture below:
![image](https://user-images.githubusercontent.com/22053634/98359975-5662de00-2029-11eb-9360-772a567dc1bd.png)

The only thing the user has to do, beside inserting and properly linking the missing triplets, is to explicitly work on the two rests indicated by orange arrows in the upper picture. Because these rests are outside any reasonable lookup area defined on beams, they don't get picked up automatically (the rests on the left side are correctly handled automatically). So, it is necessary to tell the engine that each of these rests is in the same voice as say the following head chord in the beam group.

To do that, select rest and head, then use the popup Chords menu to set them as "**Same Voice**".

FYI, to prevent a rest to get incorrectly picked up in a similar configuration, the user can simply set "**Separate Voice**" between a head of the beam group and the undesired rest.

I will soon push this commit.

**Comment by rodolfo-medina** [comment] 2020-11-06 13:29
thanks...  Is it required the development branch...?  with my `stable' version it does not seem to work...

**Comment by rodolfo-medina** [comment] 2020-11-06 13:35
I mean, it is possible to set "same voice" in the popup Chords menu, but then the coloured view shows instead that they are still separate voices...

**Comment by hbitteur** [comment] 2020-11-06 14:15
Before I actually **push** the commit, it is not publicly available.
This will be done this afternoon (Paris local time), be patient.

**Comment by hbitteur** [comment] 2020-11-06 17:51
Done, see commit d3bd072069e3f47302ecc225a4494d8bc3089bd3 
You can pull and build from the "development" branch.

Right now, I can't see any way to fix the "abnormal" red status of triplets with 4 items.
I'll leave it for a future work.

**Comment by rodolfo-medina** [comment] 2020-11-06 22:35
fantastic...!  thanks, hbitteur...  ;-)

**Comment by rodolfo-medina** [comment] 2020-11-07 13:56
From the same score, please help with page 5: it won't compile although I cleaned it up from time errors...  I wanted to attach my omr file but it seems not to be possible...  thanks

**Comment by rodolfo-medina** [comment] 2020-11-20 16:13
Another different approach could be to leave the 6/8 time in the right hand and switch to 2/4 only in the the left hand...  Could it be possible for Audiveris...?

**Comment by hbitteur** [comment] 2020-11-20 16:19
I think this would ruin the notion of time signature.
My understanding is that all measures in the same stack (vertical alignment of measures in the same system) should have the same time signature.
Moreover, 6/8 and 2/4 would not lead to the same duration!

**Comment by rodolfo-medina** [comment] 2020-11-20 16:22
All right...  I asked because in the score it is like this: switch to 2/4 only in left hand...

**Comment by rodolfo-medina** [comment] 2020-11-20 21:04
Please help with first measure of page 2 of PDF below: all the bonds seem ok but the measure background remains red...  Why?

![screenshot 2020-11-20 21:01:17](https://user-images.githubusercontent.com/64352612/99849659-d6ce2680-2b73-11eb-9b66-6cbaa0feb8d3.png)

[schumann-kreisleriana_op16n8.pdf](https://github.com/Audiveris/audiveris/files/5576072/schumann-kreisleriana_op16n8.pdf)

**Comment by hbitteur** [comment] 2020-11-21 10:59
Here is "my" result on the same measure:
![image](https://user-images.githubusercontent.com/22053634/99875391-8ac0c780-2bef-11eb-91b3-f21dcb7ef0b0.png)

Notice that I manually inserted a 2/4 time signature (I had not processed sheet 1 which exhibits a 2/4 in its last system, but went directly to sheet 2).
I also had to fix the beam group in the lower right corner (right chord and beam were missing).
And finally, to squeeze all the upper chords into 2/4, I manually inserted and linked two triplets.

Then I saved my work before going to next measure, but there the sheet display got frozen, and just this sheet. If I close and reopen the book, everything gets back to normal. Very strange, I need to fix this bug ASAP.

**Comment by rodolfo-medina** [comment] 2020-11-21 12:46
For me it remains red, also inserting the 2/4 time signature...

**Comment by hbitteur** [comment] 2020-11-21 17:08
FYI: The bug related to sheet frozen display is now fixed (see issue #445).

**Comment by hbitteur** [comment] 2020-11-21 17:13
Inserting the 2/4 was needed because I wanted to work on this sheet in isolation.
But manually inserting the 2 triplets is definitely needed.
To check your measure timing, use a right click in the measure at hand, and select "Measures ... | Dump voices".
This will give you a strip-kind display of your measure. Don't hesitate to post it here.

**Comment by rodolfo-medina** [comment] 2020-11-21 17:23
thanks...  here it is (I'm afraid it's a bit hard for me):

MeasureStack#1
    |0       |1/12    |1/8     |1/6     |1/4     |1/3     |3/8     |5/12    |1/2     |5/8
--- P1
V 5 |Ch#9031 |Ch#12508|Ch#9016 |Ch#9017 |Ch#9018 |Ch#12509|Ch#9034 |Ch#9035 |........|1/2 (ts:2/4)
V 6 |Ch#9032 ===========================|Ch#9033 =========|Ch#13142=========|Ch#13145|5/8

**Comment by hbitteur** [comment] 2020-11-21 17:29
Rather unreadable. Could you put the strip between &lt;pre&gt; and  &lt;/pre&gt; tags?

**Comment by rodolfo-medina** [comment] 2020-11-21 17:37
<pre> and </pre> tags...?

**Comment by rodolfo-medina** [comment] 2020-11-21 17:42
<pre>
MeasureStack#1
|0 |1/12 |1/8 |1/6 |1/4 |1/3 |3/8 |5/12 |1/2 |5/8
--- P1
V 5 |Ch#9031 |Ch#12508|Ch#9016 |Ch#9017 |Ch#9018 |Ch#12509|Ch#9034 |Ch#9035 |........|1/2 (ts:2/4)
V 6 |Ch#9032 ===========================|Ch#9033 =========|Ch#13142=========|Ch#13145|5/8
</pre>

**Comment by hbitteur** [comment] 2020-11-21 17:49
The purpose is to force markdown to present the lines as they are (**pre**sentation) with no fancy layout.
This means something like "as it is".
For example if I type 
<pre>
MeasureStack#1
    |0       |1/12    |1/8     |1/6     |1/4     |1/3     |3/8     |5/12    |1/2
--- P1
V 5 |Ch#9929 |Ch#13401|Ch#9914 |Ch#9915 |Ch#9916 |Ch#13402|Ch#9932 |Ch#9933 |1/2 (ts:2/4)
V 6 |Ch#9930 ===========================|Ch#9931 =========|Ch#12247=========|1/2 (ts:2/4)
</pre>
I get:
MeasureStack#1
    |0       |1/12    |1/8     |1/6     |1/4     |1/3     |3/8     |5/12    |1/2
--- P1
V 5 |Ch#9929 |Ch#13401|Ch#9914 |Ch#9915 |Ch#9916 |Ch#13402|Ch#9932 |Ch#9933 |1/2 (ts:2/4)
V 6 |Ch#9930 ===========================|Ch#9931 =========|Ch#12247=========|1/2 (ts:2/4)

While, with:
<pre>
&lt;pre&gt;
MeasureStack#1
    |0       |1/12    |1/8     |1/6     |1/4     |1/3     |3/8     |5/12    |1/2
--- P1
V 5 |Ch#9929 |Ch#13401|Ch#9914 |Ch#9915 |Ch#9916 |Ch#13402|Ch#9932 |Ch#9933 |1/2 (ts:2/4)
V 6 |Ch#9930 ===========================|Ch#9931 =========|Ch#12247=========|1/2 (ts:2/4)
&lt;/pre&gt;
</pre>
I get:
<pre>
MeasureStack#1
    |0       |1/12    |1/8     |1/6     |1/4     |1/3     |3/8     |5/12    |1/2
--- P1
V 5 |Ch#9929 |Ch#13401|Ch#9914 |Ch#9915 |Ch#9916 |Ch#13402|Ch#9932 |Ch#9933 |1/2 (ts:2/4)
V 6 |Ch#9930 ===========================|Ch#9931 =========|Ch#12247=========|1/2 (ts:2/4)
</pre>

**Comment by rodolfo-medina** [comment] 2020-11-21 17:53
is it ok...?

<pre>
MeasureStack#1
|0 |1/12 |1/8 |1/6 |1/4 |1/3 |3/8 |5/12 |1/2 |5/8
--- P1
V 5 |Ch#9031 |Ch#12508|Ch#9016 |Ch#9017 |Ch#9018 |Ch#12509|Ch#9034 |Ch#9035 |........|1/2 (ts:2/4)
V 6 |Ch#9032 ===========================|Ch#9033 =========|Ch#13142=========|Ch#13145|5/8
</pre>

**Comment by hbitteur** [comment] 2020-11-21 17:54
Yes, sorry, our messages crossed.
One line is still not readable: the one right under "MeasureStack":
|0 |1/12 |1/8 |1/6 |1/4 |1/3 |3/8 |5/12 |1/2 |5/8
should have its items aligned with the time slots below (see my examples)

**Comment by hbitteur** [comment] 2020-11-21 18:01
Anyway, the problem is you have a sequence of 4 chords in voice V6, while I have only 3.
What is this 4th chord 13145 (enter this id in the Inter board, Audiveris will point to the chord)

**Comment by rodolfo-medina** [comment] 2020-11-21 18:01
sorry, I don't manage to adjust it...

**Comment by hbitteur** [comment] 2020-11-21 18:02
Not problem with layout, I was able to adjust it on my side

**Comment by rodolfo-medina** [comment] 2020-11-21 18:06
yes, Audiveris pointed there:

![screenshot 2020-11-21 18:05:37](https://user-images.githubusercontent.com/64352612/99884202-3ab02800-2c24-11eb-9369-f90359fd836f.png)

in the rectangle, can you see it?

**Comment by rodolfo-medina** [comment] 2020-11-21 18:08
yes, Audiveris pointed there:
![screenshot 2020-11-21 18:07:01](https://user-images.githubusercontent.com/64352612/99884217-692e0300-2c24-11eb-8a54-dbb59bfc9ac7.png)


in the rectangle, can you see it?

**Comment by rodolfo-medina** [comment] 2020-11-21 18:09
White...!!

**Comment by hbitteur** [comment] 2020-11-21 18:10
Well it's the 3rd chord.
You have only 3 chords in the lower part of the measure. Please check each of the **4** chords that appear as V6 in measure strip.
Where is precisely each of them?

**Comment by rodolfo-medina** [comment] 2020-11-21 18:11
Now the measure background is become white, after I deleted and then put again the lower pitch of that chord...

**Comment by hbitteur** [comment] 2020-11-21 18:11
Activate voice coloring (on the tool bar). This should help

**Comment by rodolfo-medina** [comment] 2020-11-21 18:11
it's ok now, it's white...

**Comment by hbitteur** [comment] 2020-11-21 18:15
Good news, at last!
I'm returning to my work on poor scores. I really need to complete this work (it should be helpful on your example, by the way).
Bye
/Hervé

**Comment by rodolfo-medina** [comment] 2020-11-21 18:16
thank you...  good work!

rodolfo

**Comment by rodolfo-medina** [comment] 2020-11-21 22:07
This measure now on p.3 is corrupted, I think...  How to work it out?

![screenshot 2020-11-21 22:06:03](https://user-images.githubusercontent.com/64352612/99888603-f3d32a00-2c45-11eb-8900-c43d3edb4cbd.png)

**Comment by rodolfo-medina** [comment] 2020-11-22 09:59
...It happens any time I try to "merge" a chord: the measure goes to necrosis and can't be took back again...

**Comment by hbitteur** [comment] 2020-11-24 10:30
@rodolfo-medina 
Issue management is meant to formalize and handle issues.

I have already helped you on dealing with examples of yours, but I can't keep on doing this forever. You are on your own now with the current tools of Audiveris UI.

Sorry, I still have significant work to carry out for the coming release.

**Comment by rodolfo-medina** [comment] 2020-11-24 13:43
Sorry...  I didn't mean to take you time off other more important issues...  I'm learning more and more in using Audiveris and feel more and more sure with it.  One thing I don't yet understand is how to get back to life a measure that during the editing got to "necrosis" i.e. corrupted or something similar...  Maybe some other user could be able to help about that...  Thanks for what you are doing and for your precious work with wonderful Audiveris.

**Comment by hbitteur** [comment] 2020-11-24 15:20
I know the documentation is not up-to-date for coming 5.2, it's on the todo list.

Anytime you modify something that could impact a measure rhythm, for example adding / deleting notes or many other things, the measure is automatically reprocessed (as well as all the other measures potentially impacted, for example when modifying a time signature).

You can also manually trigger the rhythm re-processing of a measure, by pointing on this measure and using a right-click to get the contextual popup menu. There you can select the "Reprocess Measure" item.
Also, similar manual re-process is available at page level via "Reprocess Page".

**Comment by rodolfo-medina** [comment] 2020-11-25 08:50
Any operation and modification on that "dead" measure, also reprocessing rythm, fails with:

StackRhythm error processing MeasureStack#6 java.lang.NullPointerException

**Closed** 2021-08-06 12:36 UTC
