### ISSUE TITLE
Compatibility with tesseract 4

### ISSUE THREAD

**Issue by deepio** [Audiveris/audiveris#273] opened 2019-04-06 23:37 UTC
- Audiveris: `5.1.0:6780b1f91`
- __OCR Engine:   `Tesseract OCR, version 3.04.01`__

When will we see support for Tesseract `4.0`?

**Comment by maximumspatium** [comment] 2019-04-07 00:37
> When will we see support for Tesseract 4.0?

I'm currently working on supporting Tesseract 4.0. Unfortunately, an upgrade attempt has revealed unforeseen problems:

- an old "won't fix" bug has slipped into the 4.x branch causing Java Virtual Machine to crash when accessing libtesseract. The problem is that Tesseract maintainers stubbornly refuse to fix this issue repeatedly telling "that is not our bug" and thus just breaking 3rd party software. Fortunately, Samuel Audet from Javacpp project has recently fixed it, see https://github.com/bytedeco/javacpp-presets/issues/694
- Tesseract public API seems to have undergone some changes so the way Audiveris communicate with the engine doesn't work anymore. This need to be troubleshoot and worked around.

Moreover, Tesseract's full page mode has been proven to perform rather poor on text recognition in presence of musical symbols. Especially, lyrics and chords are often affected because they use uncommon layout vs. grammar. This is something we cannot work around easily. For the time being, Audiveris let Tesseract to perform one-shot text detection and recognition relying on algorithms we have no control over. This need to be reworked to allow multistage recognition/rejection using different parameters, see #44.

**Comment by maximumspatium** [comment] 2019-05-11 12:40
Update:

> 1. (JVM crash)

fixed

> 2. Tesseract public API seems to have undergone some changes so the way Audiveris communicate with the engine doesn't work anymore.

Audiveris relies on the information returned by `LTRResultIterator::WordFontAttributes` that includes font properties (bold, italic etc) as well as font size. All this is required by the Audiveris UI for displaying recognized text over the original picture.

Tesseract 4 has been redesigned in such a way that the font information except character size isn't available anymore, see https://github.com/tesseract-ocr/tesseract/issues/1074

A support for font attributes is feasible but isn't available yet. According to the principal Tesseract developer, Ray Smith, this is one more reason for delaying deprecation of the v3 engine.

Many people recommend to stick to the old engine instead of switching to the recent one. The reality is a bit different:

- most of the package managers already switched to Tesseract 4; installing the older version is somewhat difficult requiring compiling from sources
- Tesseract shows an improved accuracy and faster recognition for musical scores than its predecessor

I'm currently redesigning Tesseract-related classes to support the new engine. Results will be reported in short...

**Comment by maximumspatium** [comment] 2019-05-25 12:08
After spending several days analyzing Tesseract's 4 output via TessAPI, I found out several heavy-weight problems preventing further adoption of the LSTM engine for our OMR task.
The biggest roadblock is that Tesseract 4 reports sometimes random characters with bounding box set to the whole page. This is a known issue reported by several people and still unfixed, see https://github.com/tesseract-ocr/tesseract/issues/1192

I therefore decide to wait for the Tesseract team to fix all bounding box related issues first. Audiveris will stick to Tesseract 3.x for now.

**Comment by maximumspatium** [comment] 2019-06-28 14:58
I just tested Tesseract 4 in the legacy engine mode (OEM_TESSERACT_ONLY). It seems to work as expected. The updated code was pushed to the [tess4](https://github.com/Audiveris/audiveris/commits/tess4) feature branch.

Please test it and give me a feedback.

**Comment by deepio** [comment] 2019-07-03 15:42
I can confirm that it does not crash and it produces musicxml files, but the files are almost completely empty.

**Comment by deepio** [comment] 2020-04-18 02:05
Will close this issue and create a new one for the new issue.

**Comment by stweil** [comment] 2022-01-09 15:52
> I just tested Tesseract 4 in the legacy engine mode (OEM_TESSERACT_ONLY). It seems to work as expected.

That's what I have expected, too. Tesseract 4 and even the latest Tesseract 5.0.1 are still compatible with Tesseract 3 in legacy mode. Why was the update abandoned? I noticed that there exist pre-built jar files which can be used for 4.0.0, but I could not find jar files for newer releases.

**Comment by stweil** [comment] 2022-01-09 16:31
Now I could at least build with Tesseract 4.1.1 (based on your tess4 branch). See https://github.com/stweil/audiveris/tree/tess4.

**Comment by hbitteur** [comment] 2022-01-09 18:21
@stweil 
While investigating a new classifier in mid 2020 (see head-classifier branch), I used Tesseract 4.1.0 to be able to build the whole software set.

But I did not really use OCR by this time, I was focusing on a new attempt of head recognition via a patch classifier. This work is still on pause right now, it should get resurrected some day, but that's another story.
Purpose of my remark is to call your attention on the fact that the software can be built, but that says nothing about the quality of OCR recognition (vs the 3.x Tesseract engine) when applied to sparse textual elements as found on a music score.

If you could spend some time to evaluate the actual OCR results (of 4.x, and perhaps 5.x as you mentioned), we would all benefit from such experience.

**Comment by stweil** [comment] 2022-01-09 18:29
In theory Tesseract 4 and 5 in legacy mode should produce identical results as Tesseract 3, so the quality would be identical. Tesseract 5 would still be faster, include a lot of bug fixes and support more platforms (ARM, Apple M1, ...).

I have much experience with Tesseract, so I can help on that side. And I have no experience with Audiveris.

**Comment by maximumspatium** [comment] 2022-01-09 18:44
@hbitteur Stefan asked for the reason to not merging the `tess4` branch into `master`/`development`.
As for now, Audiveris still uses the ancient Tesseract 3.04, see https://github.com/Audiveris/audiveris/blob/8671b0957f2f52e88f428fac8d75bb7ae34dfe78/build.gradle#L14

To my understanding, nothing prevent us from switching to the newer Tesseract 4.1 or even 5.x as long as they run in the legacy engine mode. This will require changes available in the `tess4` branch because the underlying API for accessing the new OCR engine was updated several years ago.

**Comment by maximumspatium** [comment] 2022-01-09 18:48
@stweil 

> I noticed that there exist pre-built jar files which can be used for 4.0.0, but I could not find jar files for newer releases.

Audiveris doesn't use pre-built binaries. It uses the [javacpp-presets](https://github.com/bytedeco/javacpp-presets) wrapper for accessing Tesseract. The recent `javacpp-presets` release supports Tesseract 5.0 by default.

**Comment by hbitteur** [comment] 2022-01-09 19:02
@maximumspatium 
Yes, let's try to move to 5.x in legacy mode

**Comment by maximumspatium** [comment] 2022-01-09 19:04
I'll go ahead and switch to `javacpp-presets` 1.5.6 then.

**Comment by stweil** [comment] 2022-01-09 19:11
I just tried Audiveris with 4.1.1, and that seems to work fine. The modifications from your `tess4` branch were sufficient (I only rebased those changes to the latest code in https://github.com/stweil/audiveris/tree/tess4).

**Comment by maximumspatium** [comment] 2022-04-20 22:23
@stweil I finally switched Audiveris to Tesseract 4.1.1, see https://github.com/Audiveris/audiveris/commit/ce976106850aded17558af14116d5d89c54e37a4

I also tried Audiveris with Tesseract 5.0.1. Unfortunately, `libtesseract` crashes the JVM in my macOS 10.13, probably because the binaries were compiled for macOS 10.15. I need to rebuild Javacpp-presets for my system to be able to test the recent OCR engine.

**Comment by maximumspatium** [comment] 2022-04-20 22:37
> I have much experience with Tesseract, so I can help on that side

@stweil We're experiencing issues with Tesseract sometimes reporting unreliable symbol positions  when running in the full page mode.
Original image:
![Original text](https://user-images.githubusercontent.com/6561800/164335985-41cc4958-2f68-4e1c-9468-e8edd819301e.png)

Recognition result:
![Recognized Text with wrong letter positions](https://user-images.githubusercontent.com/6561800/164336007-a3e648c6-c4af-4c53-8f21-7e24fbd93e4e.png)

Selecting the area and letting Tesseract recognize it again usually produces better results:
![Fixed Text](https://user-images.githubusercontent.com/6561800/164336035-b9739c50-7aa8-4fdb-87b0-9cd875d97cf6.png)

It looks like a bug in the Tesseract API I never managed to catch.
Any idea how to fix that?

**Comment by stweil** [comment] 2022-04-22 09:18
Do you get those wrong positions also when the same page is processed by the `tesseract` executable?

**Comment by maximumspatium** [comment] 2022-04-23 19:01
> Do you get those wrong positions also when the same page is processed by the tesseract executable?

The `tesseract` executable reports correct symbol positions in the XML output.

I tried two different segmentation modes and got the following results:

PSM=3, Tesseract's default, also used by Audiveris:

```xml
<TextLine ID="line_3" HPOS="139" VPOS="392" WIDTH="536" HEIGHT="39">
   <String ID="string_10" HPOS="139" VPOS="392" WIDTH="226" HEIGHT="39" WC="0.84" CONTENT="Arrangement"/><SP WIDTH="14" VPOS="392" HPOS="365"/>
   <String ID="string_11" HPOS="379" VPOS="402" WIDTH="4" HEIGHT="21" WC="0.89" CONTENT=":"/><SP WIDTH="16" VPOS="402" HPOS="383"/>
   <String ID="string_12" HPOS="399" VPOS="392" WIDTH="94" HEIGHT="31" WC="0.83" CONTENT="Alain"/><SP WIDTH="12" VPOS="392" HPOS="493"/>
   <String ID="string_13" HPOS="505" VPOS="393" WIDTH="170" HEIGHT="30" WC="0.89" CONTENT="BRUNET"/>
</TextLine>
```

PSM=11 i.e. "find as much test as possible":

```xml
<TextLine ID="line_2" HPOS="139" VPOS="392" WIDTH="536" HEIGHT="39">
   <String ID="string_8" HPOS="139" VPOS="392" WIDTH="226" HEIGHT="39" WC="0.82" CONTENT="Arrangement"/><SP WIDTH="14" VPOS="392" HPOS="365"/>
   <String ID="string_9" HPOS="379" VPOS="402" WIDTH="4" HEIGHT="21" WC="0.89" CONTENT=":"/><SP WIDTH="16" VPOS="402" HPOS="383"/>
   <String ID="string_10" HPOS="399" VPOS="392" WIDTH="94" HEIGHT="31" WC="0.83" CONTENT="Alain"/><SP WIDTH="12" VPOS="392" HPOS="493"/>
   <String ID="string_11" HPOS="505" VPOS="393" WIDTH="170" HEIGHT="30" WC="0.89" CONTENT="BRUNET"/>
</TextLine>
```
![tessimg](https://user-images.githubusercontent.com/6561800/164942721-588a74a5-fbfe-4796-934e-6779a2f35ac2.png)

I assume a bug somewhere in the public API.

**Comment by stweil** [comment] 2022-04-24 07:49
> @stweil I finally switched Audiveris to Tesseract 4.1.1, see [ce97610](https://github.com/Audiveris/audiveris/commit/ce976106850aded17558af14116d5d89c54e37a4)

I just wanted to try the new code, but it looks like the Javacpp-presets are unavailable for M1 MacOS.

**Comment by maximumspatium** [comment] 2022-04-24 13:14
> I just wanted to try the new code, but it looks like the Javacpp-presets are unavailable for M1 MacOS.

@stweil That's true. Apparently, it's very easy to build Javacpp-presets yourself. Each preset includes a build script that compiles both the native library as well as its JNI bridge. Unfortunately, I can't do it because I don't own a M1 Mac :)
Anyway,  I compiled Javacpp-presets from source several times in the past. I was pretty easy.

FYI: https://github.com/bytedeco/javacpp-presets/issues/1069

**Comment by maximumspatium** [comment] 2022-04-24 20:10
Let's move our discussion regarding OCR issues to #575.

**Closed by maximumspatium** 2022-04-24 20:10 UTC

**Comment by saudet** [comment] 2022-05-09 13:02
FYI, `macosx-arm64` builds are now available, see issue https://github.com/bytedeco/javacpp-presets/issues/814.
Please give it a try with the snapshots: http://bytedeco.org/builds/
