### ISSUE TITLE
Error computing SuiteImpacts on stick#9279 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by hallvors** [Audiveris/audiveris#479] opened 2021-03-26 21:59 UTC
This error stops the processing of a PDF score. 
Any way I can help provide more information here?

```
WARN  [Score - Bandology#3]              SuiteImpacts 135  | Error computing SuiteImpacts on stick#9279
java.lang.NullPointerException: null
	at org.audiveris.omr.glyph.Glyph.getStartPoint(Glyph.java:423)
	at org.audiveris.omr.sheet.stem.VerticalsBuilder$SlopeCheck.getValue(VerticalsBuilder.java:608)
	at org.audiveris.omr.sheet.stem.VerticalsBuilder$SlopeCheck.getValue(VerticalsBuilder.java:588)
	at org.audiveris.omr.check.Check.pass(Check.java:233)
	at org.audiveris.omr.check.CheckSuite.pass(CheckSuite.java:296)
	at org.audiveris.omr.check.SuiteImpacts.newInstance(SuiteImpacts.java:131)
	at org.audiveris.omr.check.CheckSuite.getImpacts(CheckSuite.java:221)
	at org.audiveris.omr.sheet.stem.VerticalsBuilder.checkStem(VerticalsBuilder.java:178)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.createStemInter(HeadLinker.java:601)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.includeItems(HeadLinker.java:981)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.link(HeadLinker.java:345)
	at org.audiveris.omr.sheet.stem.HeadLinker.linkStemCorners(HeadLinker.java:165)
	at org.audiveris.omr.sheet.stem.StemsBuilder.linkStems(StemsBuilder.java:273)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:59)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:37)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:193)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:176)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:214)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:101)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1219)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
WARN  [Score - Bandology#3]              SuiteImpacts 135  | Error computing SuiteImpacts on stick#9279
java.lang.NullPointerException: null
	at org.audiveris.omr.glyph.Glyph.getStartPoint(Glyph.java:423)
	at org.audiveris.omr.sheet.stem.VerticalsBuilder$SlopeCheck.getValue(VerticalsBuilder.java:608)
	at org.audiveris.omr.sheet.stem.VerticalsBuilder$SlopeCheck.getValue(VerticalsBuilder.java:588)
	at org.audiveris.omr.check.Check.pass(Check.java:233)
	at org.audiveris.omr.check.CheckSuite.pass(CheckSuite.java:296)
	at org.audiveris.omr.check.SuiteImpacts.newInstance(SuiteImpacts.java:131)
	at org.audiveris.omr.check.CheckSuite.getImpacts(CheckSuite.java:221)
	at org.audiveris.omr.sheet.stem.VerticalsBuilder.checkStem(VerticalsBuilder.java:178)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.createStemInter(HeadLinker.java:601)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.includeItems(HeadLinker.java:981)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.link(HeadLinker.java:345)
	at org.audiveris.omr.sheet.stem.HeadLinker.linkStemCorners(HeadLinker.java:165)
	at org.audiveris.omr.sheet.stem.StemsBuilder.linkStems(StemsBuilder.java:273)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:59)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:37)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:193)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:176)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:214)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:101)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1219)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
WARN  [Score - Bandology#3]                 SheetStub 918  | Error in performing [STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1235)
	at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:902)
	at org.audiveris.omr.sheet.SheetStub.transcribe(SheetStub.java:1144)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2215)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2198)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:221)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:101)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1219)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.createStemInter(HeadLinker.java:602)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.includeItems(HeadLinker.java:981)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.link(HeadLinker.java:345)
	at org.audiveris.omr.sheet.stem.HeadLinker.linkStemCorners(HeadLinker.java:165)
	at org.audiveris.omr.sheet.stem.StemsBuilder.linkStems(StemsBuilder.java:273)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:59)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:37)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:193)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:176)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:214)
	... 8 common frames omitted
WARN  [Score - Bandology#3]                 SheetStub 918  | Error in performing [STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1235)
	at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:902)
	at org.audiveris.omr.sheet.SheetStub.transcribe(SheetStub.java:1144)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2215)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2198)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:221)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:101)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1219)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.createStemInter(HeadLinker.java:602)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.includeItems(HeadLinker.java:981)
	at org.audiveris.omr.sheet.stem.HeadLinker$CornerLinker.link(HeadLinker.java:345)
	at org.audiveris.omr.sheet.stem.HeadLinker.linkStemCorners(HeadLinker.java:165)
	at org.audiveris.omr.sheet.stem.StemsBuilder.linkStems(StemsBuilder.java:273)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:59)
	at org.audiveris.omr.sheet.stem.StemsStep.doSystem(StemsStep.java:37)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:193)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:176)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:214)
	... 8 common frames omitted
```

Note: before the file loads, I also get this warning:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jgoodies.common.internal.RenderingUtils (file:/home/hallvord/repo/audiveris/Audiveris/lib/jgoodies-common-1.8.1.jar) to method sun.swing.SwingUtilities2.drawStringUnderlineCharAt(javax.swing.JComponent,java.awt.Graphics,java.lang.String,int,int,int)
WARNING: Please consider reporting this to the maintainers of com.jgoodies.common.internal.RenderingUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by hbitteur** [comment] 2021-03-27 18:28
The stack trace is not enough to understand what happened. Please provide the music image you were processing, so that we can reproduce and investigate the case.

Regarding the "illegal reflective access operation", this message appears as soon as you make use of GUI interface which is based on JGoodies code. It's just a warning for the time being. Maintainers of JGoodies are aware of this.

**Comment by hallvors** [comment] 2021-03-29 10:41
@hbitteur thanks, can I E-mail you the file or something? It is bought online, so I suppose I ought not to share it publicly.

**Comment by hbitteur** [comment] 2021-03-29 17:13
OK, my private mail is herve dot bitteur at audiveris dot org

**Comment by hbitteur** [comment] 2021-03-31 17:40
I got IllegalArgumentException:  Comparison method violates its general contract! during the STEMS step on your page 3.

While investigating the case, I discovered a serious flaw in the development version of STEMS step that appeared clearly with such a huge system height (the whole page).
I'm working on this. Stay tuned...

**Comment by hbitteur** [comment] 2021-04-01 16:18
Bug fixed in last commit 817a658446e0fbbc43586ef173adc984dcd8e1df
I transcribed page 3 with no more problem.
Please pull again and rebuild

I noticed that this page exhibits many triplets, which were not recognized as such in SYMBOLS step. If your whole book (24 sheets) were full of such triplets, I would recommend to incrementally train the glyph classifier (a rather advanced operation), but these triplets seem to appear in page 3 only.

You'll have to manually correct these non-recognized "3" triplet symbols. Not a big deal after all.
To do so, I'd advise you to use the "_repetitive input_" mode. This is a new feature and I don't think documentation is up-to-date on this topic:
1. Simply insert manually the first triplet symbol by dragging it from the shape palette,
2. Then press the "_repetitive_" icon (it looks like a green "+" sign on the tool bar).
3. From that point on, simply click on each and every location you like and a new triplet will be inserted at each location.
4. To exit this mode, press again on the repetitive icon.

Now, a more general remark. Perhaps this is none of my business, but since you bought this score from I suppose a music publisher, why don't you ask this publisher for the MusicXML version of the score? Rather than going through the "pixel" level with OMR.
Fortunately, Audiveris is free :-), but some manual work is still needed.
Just my 2 cents...

**Comment by hbitteur** [comment] 2021-04-01 16:44
After a closer look, I think many triplets were not recognized because your scan DPI was too low, resulting in an interline value (vertical distance between staff lines, center to center) of **11** pixels.
See the picture below:
![image](https://user-images.githubusercontent.com/22053634/113325988-669d9180-9319-11eb-9193-cd3505f2b5f7.png)
Zoomed:
![image](https://user-images.githubusercontent.com/22053634/113326223-ae241d80-9319-11eb-9396-764764e7983d.png)

Our recommendation is to select a DPI version such that the resulting interline is around **20 pixel**s.
But this music score is really crowded, and a higher DPI may lead to a huge image.

**Comment by hbitteur** [comment] 2021-04-01 17:24
While exporting this page 3 to MusicXML format, I got an error on notes that appear on the two last staves.
Both these staves start with a percussion clef. And the error occurred when trying to assign pitch (step and octave) to each of the notes on these staves.
In Audiveris code, a percussion clef gives no step/octave indication, but perhaps this is wrong. Typically, are the pitches following a percussion clef identical to a G-clef? Please help me!

**Comment by hbitteur** [comment] 2021-04-03 09:06
Bug on Percussion clef is now fixed.

I exercised Audiveris on sheet 3 of your example. There are many many triplet signs ('3') on this sheet, none was correctly recognized as such, but most of them were mistaken for a pair of staccato dots (perhaps a hundred if not more!). So, I experimented a new UI feature to let you select Inters in sheet by their shape. Then deleting all of them is just one click away.

To "select by shape", you just have to select one Inter of that shape (a staccato dot in the case at hand), and in the popup menu, navigate to "Inters...", then the inter you selected, then click on "Select all XXXXXX in sheet", where XXXXXX stands for Staccato Dot in the case at hand.
This selection today applies only at the whole sheet level. Future will tell us whether a smaller level (such as system or measure stack) could be interesting for the end user.

This feature is now available, simply pull again and build.

**Comment by hallvors** [comment] 2021-04-05 23:35
Wow, thanks a lot for the fixes. So glad the file was useful and I'll happily donate the proof-read .omr file at some point when you need those :) Unfortunately the DPI of this input file is not something I can control, but I will keep that in mind when I (hopefully) at some point start scanning actual paper notes.

**Comment by hallvors** [comment] 2021-04-05 23:40
(Also, I'd love to see more music publishers provide MusicXML files. The main source of sheet music here sadly has a _very_ small selection. Also I suppose they would ask for more money if we want to re-purchase something in a different format, although that's probably often preferable to spending time on scanning and proofing :). I'll most likely try harder to find MusicXML-supportive vendors going forward.)

**Comment by hallvors** [comment] 2021-04-06 00:38
I confirm the page 3 null pointer problem is gone!
(There's another exception on page 15 .. should I report a new issue?)

**Comment by hbitteur** [comment] 2021-04-06 06:48
I will check page 15 on my own, never mind.

**Closed** 2021-08-05 16:59 UTC
