### ISSUE TITLE
Extra voices

### ISSUE THREAD

**Issue by wil-low** [Audiveris/audiveris#34] opened 2017-11-16 05:15 UTC
Some sheet music is recognized into multiple voices. Is there a setting to tell Audiveris to avoid this? What is the logic for obviously mono-instrumental score? Thank you

**Comment by hbitteur** [comment] 2017-12-23 10:55
"_Mono-instrumental_" means there is a single _part_ (perhaps composed of 1 or 2, rarely 3 staves). And even in a mono-instrumental part, there can be several _voices_, piano and guitar are typical examples of this.

Detecting voices is something very difficult and somewhat empirical. The Dichterliebe01 score which you can find in the provided Audiveris examples, exhibits such complex voices structure.

Would you like to share your own example, as a PDF file attached to this forum, so that we have concrete material to discuss?

**Comment by wil-low** [comment] 2017-12-23 19:20
[Violin-1-Despacito.pdf](https://github.com/Audiveris/audiveris/files/1584385/Violin-1-Despacito.pdf)
PDF seems to be generated correctly but MXL file has 2 voices. I was thinking that there might be a setting to never recognize more than 1 voice if user desires.

**Comment by hbitteur** [comment] 2018-01-10 13:18
@wil-low 
I have worked on your example, which exhibits a very crowded score: some beams are very short, chords are very close abscissa-wise to the others. 
I fixed all the problems, you can check immediately by pulling the "development" branch (rather than the default "master"). 

The only exception is what is called "adjacent chords". These are chords that are so close that they should be considered as belonging to the same time slot (with different voices), rather than chords in slots sequence. In your specific case, this interpretation turns to be wrong but in many other cases it is the correct approach, so I cannot easily change the logic.
See these snapshots taken from your example to get the idea:
![adjacent chords 1](https://user-images.githubusercontent.com/22053634/34774487-cee6e084-f60f-11e7-9445-ff6fbb9294d7.png)
![adjacent chords 2](https://user-images.githubusercontent.com/22053634/34774431-966b2454-f60f-11e7-860c-8de69e99c8e8.png)

**Comment by wil-low** [comment] 2018-01-10 14:26
on this branch, when I export book as... mxl file is nearly empty
[Violin-1-Despacito.zip](https://github.com/Audiveris/audiveris/files/1619179/Violin-1-Despacito.zip)

**Comment by hbitteur** [comment] 2018-01-10 14:54
Oops, sorry. Please pull again to get the fix.

**Comment by wil-low** [comment] 2018-01-10 15:10
[Violin-1-Despacito.zip](https://github.com/Audiveris/audiveris/files/1619319/Violin-1-Despacito.zip)
weird durations when opening in EasyABC

**Comment by hbitteur** [comment] 2018-01-10 18:06
Could you check with another music editor, such as Finale or MuseScore?

**Comment by wil-low** [comment] 2018-01-10 21:24
MuseScore shows ok:

![_2018-01-10_23-19-45](https://user-images.githubusercontent.com/5940982/34796011-da4eb4a4-f65c-11e7-9b0d-7d1052a3624f.png)

Something got broken because master branch generated correct durations and EasyABC imported MXL correctly. Now it thinks all notes are thirds:

![_2018-01-10_23-18-38](https://user-images.githubusercontent.com/5940982/34796010-da27911c-f65c-11e7-8141-aa34a57eeecc.png)

**Comment by hbitteur** [comment] 2018-01-10 21:48
Here is what I get with Finale; It seems OK:
![finale](https://user-images.githubusercontent.com/22053634/34797322-55129728-f658-11e7-82c7-d5d04596e5ea.png)

**Comment by wil-low** [comment] 2018-01-10 21:58
can you fix it for easyabc too? it works in master but not in development

**Comment by hbitteur** [comment] 2018-01-10 22:07
Since MuseScore and Finale displays are correct, I suspect the problem is on easyabc side, not of the .mxl file created by Audiveris. And I don't know EasyABC at all.
I will manually inspect the content of the .mxl file tomorrow.

Also, I noticed that the text of title (Despacito) , compositor (Luis Fonsi), etc, are badly recognized on your side. As if you had bad data files for Tesseract OCR. Could you check your Tesseract material?

**Comment by wil-low** [comment] 2018-01-10 22:18
this is because I don't have Spanish file for Tesseract - nevermind

**Comment by wil-low** [comment] 2018-01-10 22:29
tried to trace a very basic tune - maybe 30 notes - from PDF generated in easyabc and import MXL back - works flawlessly. I think the issue is due to 'crowdy' Despacito which causes MXL to have unusual base duration (1/3) and confuses easyabc

**Comment by wil-low** [comment] 2018-01-10 22:59
I was wrong - master branch does not show Despacito correctly as well but it can be fixed by setting base duration to 1/8 instead of 1/4.
I think you don't need to investigate further - this is just a messy file, the worst case. Sorry for taking your time. Your application is great and powerful!

**Comment by maximumspatium** [comment] 2018-01-11 23:19
Closing because the original issue seems to have been resolved.

**Closed by maximumspatium** 2018-01-11 23:19 UTC
