### ISSUE TITLE
Build process  fails, if directory tessdata can't be found

### ISSUE THREAD

**Issue by linuxreinhard** [Audiveris/audiveris#205] opened 2018-10-17 12:39 UTC
If the tessdata directory cannot be found, gradle loops until the disc is full.
Setting TESSDATA_PREFIX to the rigth directory let the build process finish.
The buld process for audiveris-eg aborts and point to the missing path and
suggests setting TESSDATA_PREFIX.
It would be nice, if the old behavior could be restored.

Reinhard

**Comment by maximumspatium** [comment] 2018-10-24 22:59
Hmm. Can you provide more information? OS and Gradle versions to start with?

**Comment by linuxreinhard** [comment] 2018-10-25 07:00
gradle is 4.6. It was downloaded and installed by the audiveris build process.
From daemon.log of a succesfull build:
INFO  []                      Main 338  | Environment:
- Audiveris:    5.1.0:ec29281ee
- OS:           Linux 4.19.0-rc7-amd64
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01

I inserted the following line in front of gradlew:
TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/

Thanks for your great poduct!

Reinhard

**Comment by linuxreinhard** [comment] 2018-10-25 07:13
Some more information:
Distribution is Debian sid/testing; gradle from Debian (4.4.1) is not installed.
Java is Java 11.

Reinhard

**Comment by maximumspatium** [comment] 2018-10-25 11:17
Hello Reinhard,

thank you for the infos regarding your system. Now we could try to solve your issue.

First of all, the recently released Java 11 isn't currently supported by Audiveris whose code largely conforms to Java 7. Audiveris has been reported to refuse to work with JDK9/10 so it probably won't work with JDK 11 either. You'd need to downgrade to JDK 8.

Audiveris depends on Tesseract 3.x, its next version hasn't been yet tested. From the path you're passing to TESSDATA_PREFIX I infer that you're trying to feed in Tesseract 4.x language data to Tesseract 3.x. IIRC, they aren't compatible with each other.

TESSDATA_PREFIX will be checked first. If it isn't set, Audiveris should fall back to default TESSDATA paths on various OSes, see [getOcrFolder method from WellKnowns class.](https://github.com/Audiveris/audiveris/blob/ec29281ee5753276d2c353e1573497916322a23f/src/main/org/audiveris/omr/WellKnowns.java#L450-L489)
In neither case, an InstallationException will be thrown. This code has been backported to audiveris-eg so it's practically the same thing.

The case of Gradle looping forever has been already reported several times, albeit in a different context.

Can you ensure first that no conflicting Tesseract installation is present in your system?

I suggest you'd run Gradle build in debug mode and search the log for related errors/exceptions. Because Tesseract will be called during testing, it will be enough to run the test task separately with

`./gradlew clean test -d`

BTW, does `./gradlew run` work?

**Comment by linuxreinhard** [comment] 2018-10-25 12:01
Sorry, I forgot that I was using java 8 by setting JAVA_HOME in gradlew to point to java 8.

Yes, by using java 8 and setting TESSDATA_PREFIX correctly, audiveris runs succesfully.
There is no other Tesseract installation on the system.
As Debian only provides Tesseract 4 and I can use audiveris, there is no need for me to try
an older version
So I tested that audiveris can use Tesseract  4, except for the need to set  TESSDATA_PREFIX.
After setting a link to the path audiveris is looking for, I don't need the TESSDATA_PREFIX.

The only remaining point is: why is audiveris-eg giving the right error message and audiveris (without -eg) runs into the loop and fills the disc with logmessages.

Reinhard

**Comment by maximumspatium** [comment] 2018-10-25 12:18
> The only remaining point is: why is audiveris-eg giving the right error message and audiveris (without -eg) runs into the loop and fills the disc with log messages.

I cannot say for sure if this is a bug in audiveris or in JUnit/Gradle without further investigation I can't do because I never ran into this issue. Because Tesseract will be called only during testing I assume that something in the Gradle->JUnit->audiveris chain causes the infinite loop. Once again, gradle debug mode could shed more light on this...

**Comment by linuxreinhard** [comment] 2018-10-26 08:51
Sorry, I have to correct myself again. audiveris is not compatible with tesseract 4. 
As I had no interrest in text, I did not notice the error messages in the log file.
Using traineddate file for tesseract 3 I get the title too from the pdf file.

Reinhard

**Comment by maximumspatium** [comment] 2018-10-26 10:34
> Sorry, I have to correct myself again. audiveris is not compatible with tesseract 4.
As I had no interrest in text, I did not notice the error messages in the log file.
Using traineddate file for tesseract 3 I get the title too from the pdf file.

Awesome!

I was able to enforce an infinite loop during Gradle build by injecting an invalid TESSDATA path. Although this causes three audiveris tests to fail, Gradle build continues to run forever. Good catch!
I'll investigate this case and report results soon.

**Comment by maximumspatium** [comment] 2018-10-26 14:05
Endless loop is indeed caused by `InstallationException` thrown when getOcrFolder method isn't able to locate Tesseract data folder.

One of the failing tests - the ChamferMatchingTest - depends on the Shape class which, in turn, uses the Constant class. The latter relies on the ConstantManager class that imports the WellKnows class.
When the WellKnowns class is imported, all static initializers therein will be evaluated. This one will throw InstallationException in our precise case:

https://github.com/Audiveris/audiveris/blob/ec29281ee5753276d2c353e1573497916322a23f/src/main/org/audiveris/omr/WellKnowns.java#L136-L137

Because this exception is thrown within the static initializer, we will end up in `ExceptionInInitializerError` causing test class loading failure. Audiveris currently catch all derivatives of `Exception`. `ExceptionInInitializerError` doesn't belong to them and will therefore bubbled upwards until it reaches JUnit. It looks like this causes Gradle/JUnit to loop forever spitting out error messages.

The point is that no single test currently depends on Tesseract. But every test that indirectly depends on WellKnowns will fail if Tesseract data isn't available.

I therefore propose to refactor the WellKnowns class (again, sigh) not to throw exceptions during static initializations. It can cause problems with other classes, too.

**Comment by maximumspatium** [comment] 2018-10-26 15:05
>  It looks like this causes Gradle/JUnit to loop forever spitting out error messages.

**UPDATE**: endless loop actually happens in the RunTableTest class. It need to be fixed.

**Comment by hbitteur** [comment] 2018-10-29 17:11
There was a bad design in WellKnowns class which made the static elaboration of this mandatory class dependent upon  the finding of Tesseract OCR folder.  Sorry, this was my code.

Bug is now fixed in commit f166ee1a82716eabcd340d312c2245bb4730efc9 which decouples WellKnowns from OCR.

Moreover, it is now possible to run Audiveris without OCR being available. 
There is an initial warning about missing OCR and any OCR-based activity, such as the TEXTS step or a manual Lyrics/Text glyph assignment, is not effective.
But this does not prevent the program to run until completion.

**Comment by hbitteur** [comment] 2018-10-29 17:21
Oops! I forgot to remove some debug...
Real commit is 902aa739d70bd2e072cfa87dfef5b35992872c0b

**Comment by maximumspatium** [comment] 2018-10-29 23:47
Terrific! Hervé, thank you for fixing this old issue coming from 4.x era. Now the build task doesn't depend on Tesseract anymore and that's a good thing.

I'm going to close this issue now.

**Closed by maximumspatium** 2018-10-29 23:47 UTC
Labels: bug
